#!/usr/bin/env gmake

FEATFLOW=../..

include $(FEATFLOW)/Globals.mk

LIBNAME=feat3d

SRCLIST= ab03.f ab07.f ab09.f ab17.f ap3.f ap7.f ap9.f cb3h.f e010.f \
	e011.f e013.f e030.f e031.f gorsm.f gowsm.f mp311.f \
	mp330.f mp331.f mr311.f mr330.f mr331.f ndfg.f ndfgl.f ndfl.f \
	orsc.f sadb.f sb0.f sbael.f sba.f sbca.f sbcb.f sbeel.f sbe.f \
	sbvel.f sbv.f sedb.f svc.f vb0.f xmab07.f xmab17.f xmap.f \
	xmora.f xmors.f xmowa.f xmows.f xmsb0.f xmscl.f xors.f xows.f\
	xsb0x.f zfill.f zvalue.f

include $(FEATFLOW)/Rules_libs.mk