      SUBROUTINE SVC(DCOR,KNPR,NVT,PARX,PARY,PARZ)
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION DCOR(3,*),KNPR(*)
      EXTERNAL PARX,PARY,PARZ
C
      DO 10 IVT=1,NVT
      IBCT=KNPR(IVT)
      IF (IBCT.NE.0) THEN
       PX=PARX(DCOR(1,IVT),DCOR(2,IVT),DCOR(3,IVT),IBCT)
       PY=PARY(DCOR(1,IVT),DCOR(2,IVT),DCOR(3,IVT),IBCT)
       PZ=PARZ(DCOR(1,IVT),DCOR(2,IVT),DCOR(3,IVT),IBCT)
       DCOR(1,IVT)=PX
       DCOR(2,IVT)=PY
       DCOR(3,IVT)=PZ
      ENDIF
10    CONTINUE
C
      END
