#!/usr/bin/env gmake

FEATFLOW=../..

include $(FEATFLOW)/Globals.mk

LIBNAME=feat2d

SRCLIST= aa03.f aa07.f aa09.f ab03.f  ab07.f ab09.f ap3.f ap7.f ap9.f \
	cb1.f cb2q.f cb2t.f e000.f e001.f e002.f e003.f e004.f e010.f \
	e011.f e012.f e013.f e014.f e020.f e021.f e022.f e023.f e030.f \
	e031.f e032.f e033.f e034.f e040.f e050.f e060.f e061.f ea00.f \
	gowfm.f gowsm.f i000.f ia01.f ia02.f ia03.f ia11.f ia12.f ia13.f \
	ia21.f ia22.f ia23.f ib01.f ib02.f ib03.f ib21.f ib22.f ib23.f \
	ic01.f ic02.f ic03.f ic21.f ic22.f ic23.f id11.f id12.f id13.f \
	id21.f id22.f id23.f ie010.f ie01.f ie020.f ie02.f ie03.f \
	ie210.f ie21.f ie220.f ie22.f ie23.f ie31.f ie32.f ie33.f if11.f \
	if12.f if13.f ifd1.f ifd2.f lax1.f lax2.f lax3.f lcl1.f lcl2.f \
	lcl3.f lcp1.f lcp2.f lcp3.f ll21.f ll22.f llc1.f llc2.f lli1.f \
	lli2.f lsc1.f lsc2.f lsp1.f lsp2.f ltx1.f ltx2.f ltx3.f lvm.f \
	lws1.f lws2.f lws3.f m010.f mp0.f mp1.f mr0.f mr1.f ndfg.f \
	ndfgl.f ndfl.f oerr.f of0.f omsg.f ora.f orsc.f otrc.f owa.f \
	rc13.f rc17.f rc19.f rc23.f rc27.f rc29.f s2a.f s2c.f s2db.f \
	s2di.f s2m.f s2v.f sa0.f sa1.f sb0.f sb1.f sbd00.f sivb.f smas.f \
	sveb.f va0.f va1.f vb0.f vb1.f werr.f xgmows.f xic01.f xic02.f \
	xie01.f xie02.f xie03.f xie31.f xie32.f xie33.f xm010.f xm017.f \
	xmaa03.f xmaa07.f xmab03.f xmab07.f xmap.f xmors.f xmows.f xmsa0.f \
	xmsb0.f xmsb1.f xmscl.f xmva0.f xmva1.f xmvb0.f xmvb1.f xora.f \
	xors.f xowa.f xows.f xsa0x.f xsa1x.f xsb0x.f xsb1x.f xscl.f xsma2v.f \
	xsmacl.f yia11.f yia12.f yia13.f yid11.f yid12.f yid13.f yif11.f \
	yif12.f yif13.f ylax1.f ylax2.f ylax3.f yltx1.f yltx2.f yltx3.f \
	ymp0.f ymp1.f ymr0.f ymr1.f zclear.f zcpy.f zctype.f zdisp.f zfree.f \
	zinit.f zlen8.f zlen.f znew.f ztype.f zvalue.f \
	ii010.f  ii410.f ii210.f ij010.f xii217.f xii01.f xii410.f \
	iv017.f iv01m.f iw217.f msr2t7.f \
	if21.f if22.f if23.f if01.f if02.f if03.f m011.f sort.f cmsort.f \
	yiv21m.f iv02m.f zcheck.f mpr013.f mpr002.f

include $(FEATFLOW)/Rules_libs.mk
