!************************************************************************
!* This file contains basic data for numerical integration and handling
!* of elements.
!************************************************************************

!C NNAB denotes the maximum number of terms in the integral for the
!C integration that is performed by the element procedures.

      INTEGER NNAB, NNDER, NNCOF, NNBAS
      PARAMETER (NNAB=21, NNDER=6, NNCOF=6, NNBAS=21)
