#ifndef _HYDRO_H_
#define _HYDRO_H_

#if 0
!##############################################################################
!# ****************************************************************************
!# <name> hydro </name>
!# ****************************************************************************
!#
!# <purpose>
!# This is the hydrodynamic header file
!#
!# </purpose>
!##############################################################################
#endif

#include "../../flagship.h"


#if 0
!##############################################################################
! Number of variables
!##############################################################################
#endif

#define NVAR1D 3
#define NVAR2D 4
#define NVAR3D 5


#if 0
!##############################################################################
! Global type of system format
!##############################################################################
#endif

#define SYSTEM_SCALAR 0
#define SYSTEM_BLOCK  1


#if 0
!##############################################################################
! Global type of system coupling approach
!##############################################################################
#endif

#define SYSTEM_SEGREGATED 0
#define SYSTEM_ALLCOUPLED 1


#if 0
!##############################################################################
! Global type of dissipation
!##############################################################################
#endif

#define DISSIPATION_ZERO            0
#define DISSIPATION_SCALAR          1
#define DISSIPATION_ROE             2
#define DISSIPATION_RUSANOV         3
#define DISSIPATION_SCALAR_DSPLIT  -DISSIPATION_SCALAR
#define DISSIPATION_ROE_DSPLIT     -DISSIPATION_ROE
#define DISSIPATION_RUSANOV_DSPLIT -DISSIPATION_RUSANOV


#if 0
!##############################################################################
! Position of variables in vector of conservative variables
!
! By setting HYDRO_VARPOS_EXTERNAL it is possible to define the position of
! the conservative variables externally, e.g., in a larger solution vector.
!##############################################################################
#endif

#ifndef HYDRO_VARPOS_EXTERNAL
#if HYDRO_NDIM == 1

#define _HYDRO_DENSITY_     1
#define _HYDRO_XMOMENTUM_   2
#undef  _HYDRO_YMOMENTUM_
#undef  _HYDRO_ZMOMENTUM_
#define _HYDRO_TOTALENERGY_ 3

#elif HYDRO_NDIM == 2

#define _HYDRO_DENSITY_     1
#define _HYDRO_XMOMENTUM_   2
#define _HYDRO_YMOMENTUM_   3
#undef  _HYDRO_ZMOMENTUM_
#define _HYDRO_TOTALENERGY_ 4

#elif HYDRO_NDIM == 3 || !defined(HYDRO_NDIM)

#define _HYDRO_DENSITY_     1
#define _HYDRO_XMOMENTUM_   2
#define _HYDRO_YMOMENTUM_   3
#define _HYDRO_ZMOMENTUM_   4
#define _HYDRO_TOTALENERGY_ 5

#else

#error "Invalid spatial dimension specified!"

#endif
#endif

#if 0
!##############################################################################
! Conservative variables
!##############################################################################
#endif

#define DENSITY1(U,IDX)                  IDX(U,_HYDRO_DENSITY_)
#define DENSITY2(U,IDX,i,n1,n2)          IDX(U,_HYDRO_DENSITY_,i,n1,n2)
#define DENSITY3(U,IDX,i,j,n1,n2,n3)     IDX(U,_HYDRO_DENSITY_,i,j,n1,n2,n3)

#define XMOMENTUM1(U,IDX)                IDX(U,_HYDRO_XMOMENTUM_)
#define XMOMENTUM2(U,IDX,i,n1,n2)        IDX(U,_HYDRO_XMOMENTUM_,i,n1,n2)
#define XMOMENTUM3(U,IDX,i,j,n1,n2,n3)   IDX(U,_HYDRO_XMOMENTUM_,i,j,n1,n2,n3)

#define YMOMENTUM1(U,IDX)                IDX(U,_HYDRO_YMOMENTUM_)
#define YMOMENTUM2(U,IDX,i,n1,n2)        IDX(U,_HYDRO_YMOMENTUM_,i,n1,n2)
#define YMOMENTUM3(U,IDX,i,j,n1,n2,n3)   IDX(U,_HYDRO_YMOMENTUM_,i,j,n1,n2,n3)

#define ZMOMENTUM1(U,IDX)                IDX(U,_HYDRO_ZMOMENTUM_)
#define ZMOMENTUM2(U,IDX,i,n1,n2)        IDX(U,_HYDRO_ZMOMENTUM_,i,n1,n2)
#define ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)   IDX(U,_HYDRO_ZMOMENTUM_,i,j,n1,n2,n3)

#define TOTALENERGY1(U,IDX)              IDX(U,_HYDRO_TOTALENERGY_)
#define TOTALENERGY2(U,IDX,i,n1,n2)      IDX(U,_HYDRO_TOTALENERGY_,i,n1,n2)
#define TOTALENERGY3(U,IDX,i,j,n1,n2,n3) IDX(U,_HYDRO_TOTALENERGY_,i,j,n1,n2,n3)


#if 0
!##############################################################################
! Roe average values
!##############################################################################
#endif

#define ROE_MEAN_RATIO(ul,ur)       (sqrt(ul/ur))
#define ROE_MEAN_VALUE(ul,ur,ratio) ((ratio*ul+ur)/(ratio+RCONST(1.0)))


#if 0
!##############################################################################
! Include thermodynamic header file
!##############################################################################
#endif

#if 0
! Specify spatial dimension
#endif
#ifdef HYDRO_NDIM
#define THERMODYN_NDIM HYDRO_NDIM
#endif

#if 0
! Specify ratio of specific heats
#endif
#ifdef HYDRO_GAMMA
#define THERMODYN_GAMMA HYDRO_GAMMA
#endif

#include "../../kernel/thermodynamics.h"


#if 0
!##############################################################################
! Fluxes and matrices in 1D
!##############################################################################
#endif

#if 0
! Flux in x-direction for inviscid hydrodynamics in 1D
#endif

#define INVISCIDFLUX1_XDIR1_1D(U,IDX,u,p)  XMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_XDIR1_1D(U,IDX,u,p) (XMOMENTUM1(U,IDX)*u+p)
#define INVISCIDFLUX3_XDIR1_1D(U,IDX,u,p) (TOTALENERGY1(U,IDX)*u+p*u)

#define INVISCIDFLUX1_XDIR2_1D(U,IDX,i,n1,n2,u,p)  XMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_XDIR2_1D(U,IDX,i,n1,n2,u,p) (XMOMENTUM2(U,IDX,i,n1,n2)*u+p)
#define INVISCIDFLUX3_XDIR2_1D(U,IDX,i,n1,n2,u,p) (TOTALENERGY2(U,IDX,i,n1,n2)*u+p*u)

#define INVISCIDFLUX1_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,p)  XMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u+p)
#define INVISCIDFLUX3_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*u+p*u)

#if 0
! Flux Jacobian matrix for inviscid hydrodynamics in 1D
#endif

#define INVISCIDFLUXJACOBIMATRIX11_1D(dscale,CX,u,E) RCONST(0.0)
#define INVISCIDFLUXJACOBIMATRIX12_1D(dscale,CX,u,E) dscale*CX
#define INVISCIDFLUXJACOBIMATRIX13_1D(dscale,CX,u,E) RCONST(0.0)
#define INVISCIDFLUXJACOBIMATRIX21_1D(dscale,CX,u,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(3.0))/RCONST(2.0)*u*u*CX
#define INVISCIDFLUXJACOBIMATRIX22_1D(dscale,CX,u,E) dscale*(RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*u*CX
#define INVISCIDFLUXJACOBIMATRIX23_1D(dscale,CX,u,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CX
#define INVISCIDFLUXJACOBIMATRIX31_1D(dscale,CX,u,E) dscale*(((RCONST(HYDRO_GAMMA))-RCONST(1.0))*u*u-(RCONST(HYDRO_GAMMA))*E)*u*CX
#define INVISCIDFLUXJACOBIMATRIX32_1D(dscale,CX,u,E) dscale*((RCONST(HYDRO_GAMMA))*E-RCONST(3.0)*((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*u*u)*CX
#define INVISCIDFLUXJACOBIMATRIX33_1D(dscale,CX,u,E) dscale*(RCONST(HYDRO_GAMMA))*u*CX

#if 0
! Flux Jacobian matrix in x-direction for inviscid hydrodynamics in 1D
#endif

#define INVISCIDFLUXJACOBIMATRIX11_XDIR_1D(dscale,u,E) INVISCIDFLUXJACOBIMATRIX11_1D(dscale,RCONST(1.0),u,E)
#define INVISCIDFLUXJACOBIMATRIX12_XDIR_1D(dscale,u,E) INVISCIDFLUXJACOBIMATRIX12_1D(dscale,RCONST(1.0),u,E)
#define INVISCIDFLUXJACOBIMATRIX13_XDIR_1D(dscale,u,E) INVISCIDFLUXJACOBIMATRIX13_1D(dscale,RCONST(1.0),u,E)
#define INVISCIDFLUXJACOBIMATRIX21_XDIR_1D(dscale,u,E) INVISCIDFLUXJACOBIMATRIX21_1D(dscale,RCONST(1.0),u,E)
#define INVISCIDFLUXJACOBIMATRIX22_XDIR_1D(dscale,u,E) INVISCIDFLUXJACOBIMATRIX22_1D(dscale,RCONST(1.0),u,E)
#define INVISCIDFLUXJACOBIMATRIX23_XDIR_1D(dscale,u,E) INVISCIDFLUXJACOBIMATRIX23_1D(dscale,RCONST(1.0),u,E)
#define INVISCIDFLUXJACOBIMATRIX31_XDIR_1D(dscale,u,E) INVISCIDFLUXJACOBIMATRIX31_1D(dscale,RCONST(1.0),u,E)
#define INVISCIDFLUXJACOBIMATRIX32_XDIR_1D(dscale,u,E) INVISCIDFLUXJACOBIMATRIX32_1D(dscale,RCONST(1.0),u,E)
#define INVISCIDFLUXJACOBIMATRIX33_XDIR_1D(dscale,u,E) INVISCIDFLUXJACOBIMATRIX33_1D(dscale,RCONST(1.0),u,E)


#if 0
!##############################################################################
! Fluxes and matrices in 2D
!##############################################################################
#endif

#if 0
! Flux in x-direction for inviscid hydrodynamics in 2D
#endif

#define INVISCIDFLUX1_XDIR1_2D(U,IDX,u,p)  XMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_XDIR1_2D(U,IDX,u,p) (XMOMENTUM1(U,IDX)*u+p)
#define INVISCIDFLUX3_XDIR1_2D(U,IDX,u,p) (YMOMENTUM1(U,IDX)*u)
#define INVISCIDFLUX4_XDIR1_2D(U,IDX,u,p) (TOTALENERGY1(U,IDX)*u+p*u)

#define INVISCIDFLUX1_XDIR2_2D(U,IDX,i,n1,n2,u,p)  XMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_XDIR2_2D(U,IDX,i,n1,n2,u,p) (XMOMENTUM2(U,IDX,i,n1,n2)*u+p)
#define INVISCIDFLUX3_XDIR2_2D(U,IDX,i,n1,n2,u,p) (YMOMENTUM2(U,IDX,i,n1,n2)*u)
#define INVISCIDFLUX4_XDIR2_2D(U,IDX,i,n1,n2,u,p) (TOTALENERGY2(U,IDX,i,n1,n2)*u+p*u)

#define INVISCIDFLUX1_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,p)  XMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u+p)
#define INVISCIDFLUX3_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,p) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u)
#define INVISCIDFLUX4_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*u+p*u)

#if 0
! Flux in y-direction for inviscid hydrodynamics in 2D
#endif

#define INVISCIDFLUX1_YDIR1_2D(U,IDX,v,p)  YMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_YDIR1_2D(U,IDX,v,p) (XMOMENTUM1(U,IDX)*v)
#define INVISCIDFLUX3_YDIR1_2D(U,IDX,v,p) (YMOMENTUM1(U,IDX)*v+p)
#define INVISCIDFLUX4_YDIR1_2D(U,IDX,v,p) (TOTALENERGY1(U,IDX)*v+p*v)

#define INVISCIDFLUX1_YDIR2_2D(U,IDX,i,n1,n2,v,p)  YMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_YDIR2_2D(U,IDX,i,n1,n2,v,p) (XMOMENTUM2(U,IDX,i,n1,n2)*v)
#define INVISCIDFLUX3_YDIR2_2D(U,IDX,i,n1,n2,v,p) (YMOMENTUM2(U,IDX,i,n1,n2)*v+p)
#define INVISCIDFLUX4_YDIR2_2D(U,IDX,i,n1,n2,v,p) (TOTALENERGY2(U,IDX,i,n1,n2)*v+p*v)

#define INVISCIDFLUX1_YDIR3_2D(U,IDX,i,j,n1,n2,n3,v,p)  YMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_YDIR3_2D(U,IDX,i,j,n1,n2,n3,v,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v)
#define INVISCIDFLUX3_YDIR3_2D(U,IDX,i,j,n1,n2,n3,v,p) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v+p)
#define INVISCIDFLUX4_YDIR3_2D(U,IDX,i,j,n1,n2,n3,v,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*v+p*v)

#if 0
! Flux Jacobian matrix for inviscid hydrodynamics in 2D
#endif

#define INVISCIDFLUXJACOBIMATRIX11_2D(dscale,CX,CY,u,v,E) RCONST(0.0)
#define INVISCIDFLUXJACOBIMATRIX12_2D(dscale,CX,CY,u,v,E) dscale*CX
#define INVISCIDFLUXJACOBIMATRIX13_2D(dscale,CX,CY,u,v,E) dscale*CY
#define INVISCIDFLUXJACOBIMATRIX14_2D(dscale,CX,CY,u,v,E) RCONST(0.0)
#define INVISCIDFLUXJACOBIMATRIX21_2D(dscale,CX,CY,u,v,E) dscale*((((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(u*u+v*v)-MYNEWLINE u*u)*CX-u*v*CY)
#define INVISCIDFLUXJACOBIMATRIX22_2D(dscale,CX,CY,u,v,E) dscale*((RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*u*CX+v*CY)
#define INVISCIDFLUXJACOBIMATRIX23_2D(dscale,CX,CY,u,v,E) dscale*(u*CY-((RCONST(HYDRO_GAMMA))-RCONST(1.0))*v*CX)
#define INVISCIDFLUXJACOBIMATRIX24_2D(dscale,CX,CY,u,v,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CX
#define INVISCIDFLUXJACOBIMATRIX31_2D(dscale,CX,CY,u,v,E) dscale*((((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(u*u+v*v)-v*v)*CY-MYNEWLINE u*v*CX)
#define INVISCIDFLUXJACOBIMATRIX32_2D(dscale,CX,CY,u,v,E) dscale*(v*CX-((RCONST(HYDRO_GAMMA))-RCONST(1.0))*u*CY)
#define INVISCIDFLUXJACOBIMATRIX33_2D(dscale,CX,CY,u,v,E) dscale*(u*CX+(RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*v*CY)
#define INVISCIDFLUXJACOBIMATRIX34_2D(dscale,CX,CY,u,v,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CY
#define INVISCIDFLUXJACOBIMATRIX41_2D(dscale,CX,CY,u,v,E) dscale*(((RCONST(HYDRO_GAMMA))-RCONST(1.0))*(u*u+v*v)-(RCONST(HYDRO_GAMMA))*E)*(u*CX+v*CY)
#define INVISCIDFLUXJACOBIMATRIX42_2D(dscale,CX,CY,u,v,E) dscale*(((RCONST(HYDRO_GAMMA))*E-((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(u*u+v*v))*CX-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*u*(u*CX+v*CY))
#define INVISCIDFLUXJACOBIMATRIX43_2D(dscale,CX,CY,u,v,E) dscale*(((RCONST(HYDRO_GAMMA))*E-((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(u*u+v*v))*CY-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*v*(u*CX+v*CY))
#define INVISCIDFLUXJACOBIMATRIX44_2D(dscale,CX,CY,u,v,E) dscale*((RCONST(HYDRO_GAMMA))*(u*CX+v*CY))

#if 0
! Flux Jacobian matrix in x-direction for inviscid hydrodynamics in 2D
#endif

#define INVISCIDFLUXJACOBIMATRIX11_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX11_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX12_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX12_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX13_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX13_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX14_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX14_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX21_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX21_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX22_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX22_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX23_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX23_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX24_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX24_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX31_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX31_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX32_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX32_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX33_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX33_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX34_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX34_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX41_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX41_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX42_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX42_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX43_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX43_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX44_XDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX44_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)

#if 0
! Flux Jacobian matrix in y-direction for inviscid hydrodynamics in 2D
#endif

#define INVISCIDFLUXJACOBIMATRIX11_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX11_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX12_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX12_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX13_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX13_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX14_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX14_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX21_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX21_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX22_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX22_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX23_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX23_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX24_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX24_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX31_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX31_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX32_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX32_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX33_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX33_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX34_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX34_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX41_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX41_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX42_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX42_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX43_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX43_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define INVISCIDFLUXJACOBIMATRIX44_YDIR_2D(dscale,u,v,E) INVISCIDFLUXJACOBIMATRIX44_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)


#if 0
!##############################################################################
! Fluxes and matrices in 3D
!##############################################################################
#endif

#if 0
! Flux in x-direction for inviscid hydrodynamics in 3D
#endif

#define INVISCIDFLUX1_XDIR1_3D(U,IDX,u,p)  XMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_XDIR1_3D(U,IDX,u,p) (XMOMENTUM1(U,IDX)*u+p)
#define INVISCIDFLUX3_XDIR1_3D(U,IDX,u,p) (YMOMENTUM1(U,IDX)*u)
#define INVISCIDFLUX4_XDIR1_3D(U,IDX,u,p) (ZMOMENTUM1(U,IDX)*u)
#define INVISCIDFLUX5_XDIR1_3D(U,IDX,u,p) (TOTALENERGY1(U,IDX)*u+p*u)

#define INVISCIDFLUX1_XDIR2_3D(U,IDX,i,n1,n2,u,p)  XMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_XDIR2_3D(U,IDX,i,n1,n2,u,p) (XMOMENTUM2(U,IDX,i,n1,n2)*u+p)
#define INVISCIDFLUX3_XDIR2_3D(U,IDX,i,n1,n2,u,p) (YMOMENTUM2(U,IDX,i,n1,n2)*u)
#define INVISCIDFLUX4_XDIR2_3D(U,IDX,i,n1,n2,u,p) (ZMOMENTUM2(U,IDX,i,n1,n2)*u)
#define INVISCIDFLUX5_XDIR2_3D(U,IDX,i,n1,n2,u,p) (TOTALENERGY2(U,IDX,i,n1,n2)*u+p*u)

#define INVISCIDFLUX1_XDIR3_3D(U,IDX,i,j,n1,n2,n3,u,p)  XMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_XDIR3_3D(U,IDX,i,j,n1,n2,n3,u,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u+p)
#define INVISCIDFLUX3_XDIR3_3D(U,IDX,i,j,n1,n2,n3,u,p) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u)
#define INVISCIDFLUX4_XDIR3_3D(U,IDX,i,j,n1,n2,n3,u,p) (ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u)
#define INVISCIDFLUX5_XDIR3_3D(U,IDX,i,j,n1,n2,n3,u,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*u+p*u)

#if 0
! Flux in y-direction for inviscid hydrodynamics in 3D
#endif

#define INVISCIDFLUX1_YDIR1_3D(U,IDX,v,p)  YMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_YDIR1_3D(U,IDX,v,p) (XMOMENTUM1(U,IDX)*v)
#define INVISCIDFLUX3_YDIR1_3D(U,IDX,v,p) (YMOMENTUM1(U,IDX)*v+p)
#define INVISCIDFLUX4_YDIR1_3D(U,IDX,v,p) (ZMOMENTUM1(U,IDX)*v)
#define INVISCIDFLUX5_YDIR1_3D(U,IDX,v,p) (TOTALENERGY1(U,IDX)*v+p*v)

#define INVISCIDFLUX1_YDIR2_3D(U,IDX,i,n1,n2,v,p)  YMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_YDIR2_3D(U,IDX,i,n1,n2,v,p) (XMOMENTUM2(U,IDX,i,n1,n2)*v)
#define INVISCIDFLUX3_YDIR2_3D(U,IDX,i,n1,n2,v,p) (YMOMENTUM2(U,IDX,i,n1,n2)*v+p)
#define INVISCIDFLUX4_YDIR2_3D(U,IDX,i,n1,n2,v,p) (ZMOMENTUM2(U,IDX,i,n1,n2)*v)
#define INVISCIDFLUX5_YDIR2_3D(U,IDX,i,n1,n2,v,p) (TOTALENERGY2(U,IDX,i,n1,n2)*v+p*v)

#define INVISCIDFLUX1_YDIR3_3D(U,IDX,i,j,n1,n2,n3,v,p)  YMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_YDIR3_3D(U,IDX,i,j,n1,n2,n3,v,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v)
#define INVISCIDFLUX3_YDIR3_3D(U,IDX,i,j,n1,n2,n3,v,p) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v+p)
#define INVISCIDFLUX4_YDIR3_3D(U,IDX,i,j,n1,n2,n3,v,p) (ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v)
#define INVISCIDFLUX5_YDIR3_3D(U,IDX,i,j,n1,n2,n3,v,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*v+p*v)

#if 0
! Flux in z-direction for inviscid hydrodynamics in 3D
#endif

#define INVISCIDFLUX1_ZDIR1_3D(U,IDX,w,p)  ZMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_ZDIR1_3D(U,IDX,w,p) (XMOMENTUM1(U,IDX)*w)
#define INVISCIDFLUX3_ZDIR1_3D(U,IDX,w,p) (YMOMENTUM1(U,IDX)*w)
#define INVISCIDFLUX4_ZDIR1_3D(U,IDX,w,p) (ZMOMENTUM1(U,IDX)*w+p)
#define INVISCIDFLUX5_ZDIR1_3D(U,IDX,w,p) (TOTALENERGY1(U,IDX)*w+p*w)

#define INVISCIDFLUX1_ZDIR2_3D(U,IDX,i,n1,n2,w,p)  ZMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_ZDIR2_3D(U,IDX,i,n1,n2,w,p) (XMOMENTUM2(U,IDX,i,n1,n2)*w)
#define INVISCIDFLUX3_ZDIR2_3D(U,IDX,i,n1,n2,w,p) (YMOMENTUM2(U,IDX,i,n1,n2)*w)
#define INVISCIDFLUX4_ZDIR2_3D(U,IDX,i,n1,n2,w,p) (ZMOMENTUM2(U,IDX,i,n1,n2)*w+p)
#define INVISCIDFLUX5_ZDIR2_3D(U,IDX,i,n1,n2,w,p) (TOTALENERGY2(U,IDX,i,n1,n2)*w+p*w)

#define INVISCIDFLUX1_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,w,p)  ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,w,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*w)
#define INVISCIDFLUX3_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,w,p) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*w)
#define INVISCIDFLUX4_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,w,p) (ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)*w+p)
#define INVISCIDFLUX5_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,w,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*w+p*w)

#if 0
! Flux Jacobian matrix for inviscid hydrodynamics in 3D
#endif

#define INVISCIDFLUXJACOBIMATRIX11_3D(dscale,CX,CY,CZ,u,v,w,E) RCONST(0.0)
#define INVISCIDFLUXJACOBIMATRIX12_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*CX
#define INVISCIDFLUXJACOBIMATRIX13_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*CY
#define INVISCIDFLUXJACOBIMATRIX14_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*CZ
#define INVISCIDFLUXJACOBIMATRIX15_3D(dscale,CX,CY,CZ,u,v,w,E) RCONST(0.0)
#define INVISCIDFLUXJACOBIMATRIX21_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi)-ui*ui)*CX-MYNEWLINE ui*vi*CY-MYNEWLINE ui*wi*CZ)
#define INVISCIDFLUXJACOBIMATRIX22_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ)
#define INVISCIDFLUXJACOBIMATRIX23_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(ui*CY-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*vi*CX)
#define INVISCIDFLUXJACOBIMATRIX24_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(ui*CZ-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*wi*CX)
#define INVISCIDFLUXJACOBIMATRIX25_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CX
#define INVISCIDFLUXJACOBIMATRIX31_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi)-vi*vi)*CY-MYNEWLINE ui*vi*CX-MYNEWLINE vi*wi*CZ)
#define INVISCIDFLUXJACOBIMATRIX32_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(vi*CX-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*ui*CY)
#define INVISCIDFLUXJACOBIMATRIX33_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*vi*CY+MYNEWLINE ui*CX+MYNEWLINE wi*CZ)
#define INVISCIDFLUXJACOBIMATRIX34_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(vi*CZ-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*wi*CY)
#define INVISCIDFLUXJACOBIMATRIX35_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CY
#define INVISCIDFLUXJACOBIMATRIX41_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi)-wi*wi)*CZ-MYNEWLINE ui*wi*CX-MYNEWLINE vi*wi*CY)
#define INVISCIDFLUXJACOBIMATRIX42_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(wi*CX-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*ui*CZ)
#define INVISCIDFLUXJACOBIMATRIX43_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(wi*CY-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*vi*CZ)
#define INVISCIDFLUXJACOBIMATRIX44_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*wi*CZ+MYNEWLINE ui*CX+MYNEWLINE vi*CY)
#define INVISCIDFLUXJACOBIMATRIX45_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CZ
#define INVISCIDFLUXJACOBIMATRIX51_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(((RCONST(HYDRO_GAMMA))-RCONST(1.0))*(ui*ui+vi*vi+wi*wi)-MYNEWLINE (RCONST(HYDRO_GAMMA))*Ei)*(ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ)
#define INVISCIDFLUXJACOBIMATRIX52_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(((RCONST(HYDRO_GAMMA))*Ei-((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi))*CX-MYNEWLINE((RCONST(HYDRO_GAMMA))-RCONST(1.0))*ui*(ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ))
#define INVISCIDFLUXJACOBIMATRIX53_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(((RCONST(HYDRO_GAMMA))*Ei-((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi))*CY-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*vi*(ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ))
#define INVISCIDFLUXJACOBIMATRIX54_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(((RCONST(HYDRO_GAMMA))*Ei-((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi))*CZ-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*wi*(ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ))
#define INVISCIDFLUXJACOBIMATRIX55_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(HYDRO_GAMMA))*(ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ))

#if 0
! Flux Jacobian matrix in x-direction for inviscid hydrodynamics in 2D
#endif

#define INVISCIDFLUXJACOBIMATRIX11_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX11_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX12_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX12_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX13_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX13_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX14_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX14_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX15_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX15_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX21_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX21_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX22_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX22_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX23_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX23_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX24_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX24_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX25_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX25_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX31_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX31_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX32_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX32_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX33_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX33_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX34_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX34_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX35_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX35_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX41_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX41_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX42_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX42_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX43_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX43_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX44_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX44_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX45_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX45_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX51_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX51_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX52_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX52_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX53_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX53_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX54_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX54_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX55_XDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX55_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)

#if 0
! Flux Jacobian matrix in y-direction for inviscid hydrodynamics in 2D
#endif

#define INVISCIDFLUXJACOBIMATRIX11_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX11_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX12_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX12_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX13_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX13_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX14_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX14_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX15_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX15_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX21_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX21_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX22_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX22_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX23_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX23_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX24_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX24_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX25_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX25_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX31_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX31_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX32_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX32_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX33_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX33_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX34_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX34_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX35_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX35_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX41_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX41_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX42_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX42_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX43_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX43_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX44_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX44_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX45_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX45_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX51_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX51_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX52_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX52_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX53_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX53_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX54_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX54_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX55_YDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX55_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)

#if 0
! Flux Jacobian matrix in z-direction for inviscid hydrodynamics in 2D
#endif

#define INVISCIDFLUXJACOBIMATRIX11_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX11_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX12_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX12_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX13_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX13_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX14_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX14_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX15_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX15_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX21_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX21_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX22_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX22_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX23_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX23_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX24_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX24_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX25_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX25_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX31_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX31_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX32_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX32_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX33_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX33_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX34_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX34_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX35_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX35_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX41_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX41_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX42_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX42_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX43_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX43_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX44_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX44_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX45_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX45_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX51_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX51_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX52_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX52_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX53_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX53_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX54_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX54_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define INVISCIDFLUXJACOBIMATRIX55_ZDIR_3D(dscale,u,v,w,E) INVISCIDFLUXJACOBIMATRIX55_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)

#if HYDRO_NDIM == 1

#define INVISCIDFLUX1_XDIR1 INVISCIDFLUX1_XDIR1_1D
#define INVISCIDFLUX2_XDIR1 INVISCIDFLUX2_XDIR1_1D
#define INVISCIDFLUX3_XDIR1 INVISCIDFLUX3_XDIR1_1D

#define INVISCIDFLUX1_XDIR2 INVISCIDFLUX1_XDIR2_1D
#define INVISCIDFLUX2_XDIR2 INVISCIDFLUX2_XDIR2_1D
#define INVISCIDFLUX3_XDIR2 INVISCIDFLUX3_XDIR2_1D

#define INVISCIDFLUX1_XDIR3 INVISCIDFLUX1_XDIR3_1D
#define INVISCIDFLUX2_XDIR3 INVISCIDFLUX2_XDIR3_1D
#define INVISCIDFLUX3_XDIR3 INVISCIDFLUX3_XDIR3_1D

#define INVISCIDFLUXJACOBIMATRIX11 INVISCIDFLUXJACOBIMATRIX11_1D
#define INVISCIDFLUXJACOBIMATRIX12 INVISCIDFLUXJACOBIMATRIX12_1D
#define INVISCIDFLUXJACOBIMATRIX13 INVISCIDFLUXJACOBIMATRIX13_1D
#define INVISCIDFLUXJACOBIMATRIX21 INVISCIDFLUXJACOBIMATRIX21_1D
#define INVISCIDFLUXJACOBIMATRIX22 INVISCIDFLUXJACOBIMATRIX22_1D
#define INVISCIDFLUXJACOBIMATRIX23 INVISCIDFLUXJACOBIMATRIX23_1D
#define INVISCIDFLUXJACOBIMATRIX31 INVISCIDFLUXJACOBIMATRIX31_1D
#define INVISCIDFLUXJACOBIMATRIX32 INVISCIDFLUXJACOBIMATRIX32_1D
#define INVISCIDFLUXJACOBIMATRIX33 INVISCIDFLUXJACOBIMATRIX33_1D

#define INVISCIDFLUXJACOBIMATRIX11_XDIR INVISCIDFLUXJACOBIMATRIX11_XDIR_1D
#define INVISCIDFLUXJACOBIMATRIX12_XDIR INVISCIDFLUXJACOBIMATRIX12_XDIR_1D
#define INVISCIDFLUXJACOBIMATRIX13_XDIR INVISCIDFLUXJACOBIMATRIX13_XDIR_1D
#define INVISCIDFLUXJACOBIMATRIX21_XDIR INVISCIDFLUXJACOBIMATRIX21_XDIR_1D
#define INVISCIDFLUXJACOBIMATRIX22_XDIR INVISCIDFLUXJACOBIMATRIX22_XDIR_1D
#define INVISCIDFLUXJACOBIMATRIX23_XDIR INVISCIDFLUXJACOBIMATRIX23_XDIR_1D
#define INVISCIDFLUXJACOBIMATRIX31_XDIR INVISCIDFLUXJACOBIMATRIX31_XDIR_1D
#define INVISCIDFLUXJACOBIMATRIX32_XDIR INVISCIDFLUXJACOBIMATRIX32_XDIR_1D
#define INVISCIDFLUXJACOBIMATRIX33_XDIR INVISCIDFLUXJACOBIMATRIX33_XDIR_1D

#elif HYDRO_NDIM == 2

#define INVISCIDFLUX1_XDIR1 INVISCIDFLUX1_XDIR1_2D
#define INVISCIDFLUX2_XDIR1 INVISCIDFLUX2_XDIR1_2D
#define INVISCIDFLUX3_XDIR1 INVISCIDFLUX3_XDIR1_2D
#define INVISCIDFLUX4_XDIR1 INVISCIDFLUX4_XDIR1_2D

#define INVISCIDFLUX1_XDIR2 INVISCIDFLUX1_XDIR2_2D
#define INVISCIDFLUX2_XDIR2 INVISCIDFLUX2_XDIR2_2D
#define INVISCIDFLUX3_XDIR2 INVISCIDFLUX3_XDIR2_2D
#define INVISCIDFLUX4_XDIR2 INVISCIDFLUX4_XDIR2_2D

#define INVISCIDFLUX1_XDIR3 INVISCIDFLUX1_XDIR3_2D
#define INVISCIDFLUX2_XDIR3 INVISCIDFLUX2_XDIR3_2D
#define INVISCIDFLUX3_XDIR3 INVISCIDFLUX3_XDIR3_2D
#define INVISCIDFLUX4_XDIR3 INVISCIDFLUX4_XDIR3_2D

#define INVISCIDFLUX1_YDIR1 INVISCIDFLUX1_YDIR1_2D
#define INVISCIDFLUX2_YDIR1 INVISCIDFLUX2_YDIR1_2D
#define INVISCIDFLUX3_YDIR1 INVISCIDFLUX3_YDIR1_2D
#define INVISCIDFLUX4_YDIR1 INVISCIDFLUX4_YDIR1_2D

#define INVISCIDFLUX1_YDIR2 INVISCIDFLUX1_YDIR2_2D
#define INVISCIDFLUX2_YDIR2 INVISCIDFLUX2_YDIR2_2D
#define INVISCIDFLUX3_YDIR2 INVISCIDFLUX3_YDIR2_2D
#define INVISCIDFLUX4_YDIR2 INVISCIDFLUX4_YDIR2_2D

#define INVISCIDFLUX1_YDIR3 INVISCIDFLUX1_YDIR3_2D
#define INVISCIDFLUX2_YDIR3 INVISCIDFLUX2_YDIR3_2D
#define INVISCIDFLUX3_YDIR3 INVISCIDFLUX3_YDIR3_2D
#define INVISCIDFLUX4_YDIR3 INVISCIDFLUX4_YDIR3_2D

#define INVISCIDFLUXJACOBIMATRIX11 INVISCIDFLUXJACOBIMATRIX11_2D
#define INVISCIDFLUXJACOBIMATRIX12 INVISCIDFLUXJACOBIMATRIX12_2D
#define INVISCIDFLUXJACOBIMATRIX13 INVISCIDFLUXJACOBIMATRIX13_2D
#define INVISCIDFLUXJACOBIMATRIX14 INVISCIDFLUXJACOBIMATRIX14_2D
#define INVISCIDFLUXJACOBIMATRIX21 INVISCIDFLUXJACOBIMATRIX21_2D
#define INVISCIDFLUXJACOBIMATRIX22 INVISCIDFLUXJACOBIMATRIX22_2D
#define INVISCIDFLUXJACOBIMATRIX23 INVISCIDFLUXJACOBIMATRIX23_2D
#define INVISCIDFLUXJACOBIMATRIX24 INVISCIDFLUXJACOBIMATRIX24_2D
#define INVISCIDFLUXJACOBIMATRIX31 INVISCIDFLUXJACOBIMATRIX31_2D
#define INVISCIDFLUXJACOBIMATRIX32 INVISCIDFLUXJACOBIMATRIX32_2D
#define INVISCIDFLUXJACOBIMATRIX33 INVISCIDFLUXJACOBIMATRIX33_2D
#define INVISCIDFLUXJACOBIMATRIX34 INVISCIDFLUXJACOBIMATRIX34_2D
#define INVISCIDFLUXJACOBIMATRIX41 INVISCIDFLUXJACOBIMATRIX41_2D
#define INVISCIDFLUXJACOBIMATRIX42 INVISCIDFLUXJACOBIMATRIX42_2D
#define INVISCIDFLUXJACOBIMATRIX43 INVISCIDFLUXJACOBIMATRIX43_2D
#define INVISCIDFLUXJACOBIMATRIX44 INVISCIDFLUXJACOBIMATRIX44_2D

#define INVISCIDFLUXJACOBIMATRIX11_XDIR INVISCIDFLUXJACOBIMATRIX11_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX12_XDIR INVISCIDFLUXJACOBIMATRIX12_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX13_XDIR INVISCIDFLUXJACOBIMATRIX13_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX14_XDIR INVISCIDFLUXJACOBIMATRIX14_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX21_XDIR INVISCIDFLUXJACOBIMATRIX21_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX22_XDIR INVISCIDFLUXJACOBIMATRIX22_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX23_XDIR INVISCIDFLUXJACOBIMATRIX23_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX24_XDIR INVISCIDFLUXJACOBIMATRIX24_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX31_XDIR INVISCIDFLUXJACOBIMATRIX31_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX32_XDIR INVISCIDFLUXJACOBIMATRIX32_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX33_XDIR INVISCIDFLUXJACOBIMATRIX33_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX34_XDIR INVISCIDFLUXJACOBIMATRIX34_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX41_XDIR INVISCIDFLUXJACOBIMATRIX41_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX42_XDIR INVISCIDFLUXJACOBIMATRIX42_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX43_XDIR INVISCIDFLUXJACOBIMATRIX43_XDIR_2D
#define INVISCIDFLUXJACOBIMATRIX44_XDIR INVISCIDFLUXJACOBIMATRIX44_XDIR_2D

#define INVISCIDFLUXJACOBIMATRIX11_YDIR INVISCIDFLUXJACOBIMATRIX11_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX12_YDIR INVISCIDFLUXJACOBIMATRIX12_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX13_YDIR INVISCIDFLUXJACOBIMATRIX13_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX14_YDIR INVISCIDFLUXJACOBIMATRIX14_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX21_YDIR INVISCIDFLUXJACOBIMATRIX21_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX22_YDIR INVISCIDFLUXJACOBIMATRIX22_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX23_YDIR INVISCIDFLUXJACOBIMATRIX23_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX24_YDIR INVISCIDFLUXJACOBIMATRIX24_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX31_YDIR INVISCIDFLUXJACOBIMATRIX31_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX32_YDIR INVISCIDFLUXJACOBIMATRIX32_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX33_YDIR INVISCIDFLUXJACOBIMATRIX33_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX34_YDIR INVISCIDFLUXJACOBIMATRIX34_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX41_YDIR INVISCIDFLUXJACOBIMATRIX41_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX42_YDIR INVISCIDFLUXJACOBIMATRIX42_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX43_YDIR INVISCIDFLUXJACOBIMATRIX43_YDIR_2D
#define INVISCIDFLUXJACOBIMATRIX44_YDIR INVISCIDFLUXJACOBIMATRIX44_YDIR_2D

#elif HYDRO_NDIM == 3

#define INVISCIDFLUX1_XDIR1 INVISCIDFLUX1_XDIR1_3D
#define INVISCIDFLUX2_XDIR1 INVISCIDFLUX2_XDIR1_3D
#define INVISCIDFLUX3_XDIR1 INVISCIDFLUX3_XDIR1_3D
#define INVISCIDFLUX4_XDIR1 INVISCIDFLUX4_XDIR1_3D
#define INVISCIDFLUX5_XDIR1 INVISCIDFLUX5_XDIR1_3D

#define INVISCIDFLUX1_XDIR2 INVISCIDFLUX1_XDIR2_3D
#define INVISCIDFLUX2_XDIR2 INVISCIDFLUX2_XDIR2_3D
#define INVISCIDFLUX3_XDIR2 INVISCIDFLUX3_XDIR2_3D
#define INVISCIDFLUX4_XDIR2 INVISCIDFLUX4_XDIR2_3D
#define INVISCIDFLUX5_XDIR2 INVISCIDFLUX5_XDIR2_3D

#define INVISCIDFLUX1_XDIR3 INVISCIDFLUX1_XDIR3_3D
#define INVISCIDFLUX2_XDIR3 INVISCIDFLUX2_XDIR3_3D
#define INVISCIDFLUX3_XDIR3 INVISCIDFLUX3_XDIR3_3D
#define INVISCIDFLUX4_XDIR3 INVISCIDFLUX4_XDIR3_3D
#define INVISCIDFLUX5_XDIR3 INVISCIDFLUX5_XDIR3_3D

#define INVISCIDFLUX1_YDIR1 INVISCIDFLUX1_YDIR1_3D
#define INVISCIDFLUX2_YDIR1 INVISCIDFLUX2_YDIR1_3D
#define INVISCIDFLUX3_YDIR1 INVISCIDFLUX3_YDIR1_3D
#define INVISCIDFLUX4_YDIR1 INVISCIDFLUX4_YDIR1_3D
#define INVISCIDFLUX5_YDIR1 INVISCIDFLUX5_YDIR1_3D

#define INVISCIDFLUX1_YDIR2 INVISCIDFLUX1_YDIR2_3D
#define INVISCIDFLUX2_YDIR2 INVISCIDFLUX2_YDIR2_3D
#define INVISCIDFLUX3_YDIR2 INVISCIDFLUX3_YDIR2_3D
#define INVISCIDFLUX4_YDIR2 INVISCIDFLUX4_YDIR2_3D
#define INVISCIDFLUX5_YDIR2 INVISCIDFLUX5_YDIR2_3D

#define INVISCIDFLUX1_YDIR3 INVISCIDFLUX1_YDIR3_3D
#define INVISCIDFLUX2_YDIR3 INVISCIDFLUX2_YDIR3_3D
#define INVISCIDFLUX3_YDIR3 INVISCIDFLUX3_YDIR3_3D
#define INVISCIDFLUX4_YDIR3 INVISCIDFLUX4_YDIR3_3D
#define INVISCIDFLUX5_YDIR3 INVISCIDFLUX5_YDIR3_3D

#define INVISCIDFLUX1_ZDIR1 INVISCIDFLUX1_ZDIR1_3D
#define INVISCIDFLUX2_ZDIR1 INVISCIDFLUX2_ZDIR1_3D
#define INVISCIDFLUX3_ZDIR1 INVISCIDFLUX3_ZDIR1_3D
#define INVISCIDFLUX4_ZDIR1 INVISCIDFLUX4_ZDIR1_3D
#define INVISCIDFLUX5_ZDIR1 INVISCIDFLUX5_ZDIR1_3D

#define INVISCIDFLUX1_ZDIR2 INVISCIDFLUX1_ZDIR2_3D
#define INVISCIDFLUX2_ZDIR2 INVISCIDFLUX2_ZDIR2_3D
#define INVISCIDFLUX3_ZDIR2 INVISCIDFLUX3_ZDIR2_3D
#define INVISCIDFLUX4_ZDIR2 INVISCIDFLUX4_ZDIR2_3D
#define INVISCIDFLUX5_ZDIR2 INVISCIDFLUX5_ZDIR2_3D

#define INVISCIDFLUX1_ZDIR3 INVISCIDFLUX1_ZDIR3_3D
#define INVISCIDFLUX2_ZDIR3 INVISCIDFLUX2_ZDIR3_3D
#define INVISCIDFLUX3_ZDIR3 INVISCIDFLUX3_ZDIR3_3D
#define INVISCIDFLUX4_ZDIR3 INVISCIDFLUX4_ZDIR3_3D
#define INVISCIDFLUX5_ZDIR3 INVISCIDFLUX5_ZDIR3_3D

#define INVISCIDFLUXJACOBIMATRIX11 INVISCIDFLUXJACOBIMATRIX11_3D
#define INVISCIDFLUXJACOBIMATRIX12 INVISCIDFLUXJACOBIMATRIX12_3D
#define INVISCIDFLUXJACOBIMATRIX13 INVISCIDFLUXJACOBIMATRIX13_3D
#define INVISCIDFLUXJACOBIMATRIX14 INVISCIDFLUXJACOBIMATRIX14_3D
#define INVISCIDFLUXJACOBIMATRIX15 INVISCIDFLUXJACOBIMATRIX15_3D
#define INVISCIDFLUXJACOBIMATRIX21 INVISCIDFLUXJACOBIMATRIX21_3D
#define INVISCIDFLUXJACOBIMATRIX22 INVISCIDFLUXJACOBIMATRIX22_3D
#define INVISCIDFLUXJACOBIMATRIX23 INVISCIDFLUXJACOBIMATRIX23_3D
#define INVISCIDFLUXJACOBIMATRIX24 INVISCIDFLUXJACOBIMATRIX24_3D
#define INVISCIDFLUXJACOBIMATRIX25 INVISCIDFLUXJACOBIMATRIX25_3D
#define INVISCIDFLUXJACOBIMATRIX31 INVISCIDFLUXJACOBIMATRIX31_3D
#define INVISCIDFLUXJACOBIMATRIX32 INVISCIDFLUXJACOBIMATRIX32_3D
#define INVISCIDFLUXJACOBIMATRIX33 INVISCIDFLUXJACOBIMATRIX33_3D
#define INVISCIDFLUXJACOBIMATRIX34 INVISCIDFLUXJACOBIMATRIX34_3D
#define INVISCIDFLUXJACOBIMATRIX35 INVISCIDFLUXJACOBIMATRIX35_3D
#define INVISCIDFLUXJACOBIMATRIX41 INVISCIDFLUXJACOBIMATRIX41_3D
#define INVISCIDFLUXJACOBIMATRIX42 INVISCIDFLUXJACOBIMATRIX42_3D
#define INVISCIDFLUXJACOBIMATRIX43 INVISCIDFLUXJACOBIMATRIX43_3D
#define INVISCIDFLUXJACOBIMATRIX44 INVISCIDFLUXJACOBIMATRIX44_3D
#define INVISCIDFLUXJACOBIMATRIX45 INVISCIDFLUXJACOBIMATRIX45_3D
#define INVISCIDFLUXJACOBIMATRIX51 INVISCIDFLUXJACOBIMATRIX51_3D
#define INVISCIDFLUXJACOBIMATRIX52 INVISCIDFLUXJACOBIMATRIX52_3D
#define INVISCIDFLUXJACOBIMATRIX53 INVISCIDFLUXJACOBIMATRIX53_3D
#define INVISCIDFLUXJACOBIMATRIX54 INVISCIDFLUXJACOBIMATRIX54_3D
#define INVISCIDFLUXJACOBIMATRIX55 INVISCIDFLUXJACOBIMATRIX55_3D

#define INVISCIDFLUXJACOBIMATRIX11_XDIR INVISCIDFLUXJACOBIMATRIX11_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX12_XDIR INVISCIDFLUXJACOBIMATRIX12_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX13_XDIR INVISCIDFLUXJACOBIMATRIX13_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX14_XDIR INVISCIDFLUXJACOBIMATRIX14_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX15_XDIR INVISCIDFLUXJACOBIMATRIX15_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX21_XDIR INVISCIDFLUXJACOBIMATRIX21_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX22_XDIR INVISCIDFLUXJACOBIMATRIX22_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX23_XDIR INVISCIDFLUXJACOBIMATRIX23_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX24_XDIR INVISCIDFLUXJACOBIMATRIX24_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX25_XDIR INVISCIDFLUXJACOBIMATRIX25_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX31_XDIR INVISCIDFLUXJACOBIMATRIX31_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX32_XDIR INVISCIDFLUXJACOBIMATRIX32_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX33_XDIR INVISCIDFLUXJACOBIMATRIX33_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX34_XDIR INVISCIDFLUXJACOBIMATRIX34_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX35_XDIR INVISCIDFLUXJACOBIMATRIX35_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX41_XDIR INVISCIDFLUXJACOBIMATRIX41_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX42_XDIR INVISCIDFLUXJACOBIMATRIX42_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX43_XDIR INVISCIDFLUXJACOBIMATRIX43_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX44_XDIR INVISCIDFLUXJACOBIMATRIX44_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX45_XDIR INVISCIDFLUXJACOBIMATRIX45_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX51_XDIR INVISCIDFLUXJACOBIMATRIX51_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX52_XDIR INVISCIDFLUXJACOBIMATRIX52_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX53_XDIR INVISCIDFLUXJACOBIMATRIX53_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX54_XDIR INVISCIDFLUXJACOBIMATRIX54_XDIR_3D
#define INVISCIDFLUXJACOBIMATRIX55_XDIR INVISCIDFLUXJACOBIMATRIX55_XDIR_3D

#define INVISCIDFLUXJACOBIMATRIX11_YDIR INVISCIDFLUXJACOBIMATRIX11_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX12_YDIR INVISCIDFLUXJACOBIMATRIX12_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX13_YDIR INVISCIDFLUXJACOBIMATRIX13_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX14_YDIR INVISCIDFLUXJACOBIMATRIX14_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX15_YDIR INVISCIDFLUXJACOBIMATRIX15_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX21_YDIR INVISCIDFLUXJACOBIMATRIX21_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX22_YDIR INVISCIDFLUXJACOBIMATRIX22_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX23_YDIR INVISCIDFLUXJACOBIMATRIX23_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX24_YDIR INVISCIDFLUXJACOBIMATRIX24_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX25_YDIR INVISCIDFLUXJACOBIMATRIX25_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX31_YDIR INVISCIDFLUXJACOBIMATRIX31_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX32_YDIR INVISCIDFLUXJACOBIMATRIX32_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX33_YDIR INVISCIDFLUXJACOBIMATRIX33_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX34_YDIR INVISCIDFLUXJACOBIMATRIX34_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX35_YDIR INVISCIDFLUXJACOBIMATRIX35_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX41_YDIR INVISCIDFLUXJACOBIMATRIX41_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX42_YDIR INVISCIDFLUXJACOBIMATRIX42_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX43_YDIR INVISCIDFLUXJACOBIMATRIX43_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX44_YDIR INVISCIDFLUXJACOBIMATRIX44_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX45_YDIR INVISCIDFLUXJACOBIMATRIX45_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX51_YDIR INVISCIDFLUXJACOBIMATRIX51_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX52_YDIR INVISCIDFLUXJACOBIMATRIX52_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX53_YDIR INVISCIDFLUXJACOBIMATRIX53_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX54_YDIR INVISCIDFLUXJACOBIMATRIX54_YDIR_3D
#define INVISCIDFLUXJACOBIMATRIX55_YDIR INVISCIDFLUXJACOBIMATRIX55_YDIR_3D

#define INVISCIDFLUXJACOBIMATRIX11_ZDIR INVISCIDFLUXJACOBIMATRIX11_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX12_ZDIR INVISCIDFLUXJACOBIMATRIX12_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX13_ZDIR INVISCIDFLUXJACOBIMATRIX13_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX14_ZDIR INVISCIDFLUXJACOBIMATRIX14_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX15_ZDIR INVISCIDFLUXJACOBIMATRIX15_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX21_ZDIR INVISCIDFLUXJACOBIMATRIX21_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX22_ZDIR INVISCIDFLUXJACOBIMATRIX22_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX23_ZDIR INVISCIDFLUXJACOBIMATRIX23_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX24_ZDIR INVISCIDFLUXJACOBIMATRIX24_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX25_ZDIR INVISCIDFLUXJACOBIMATRIX25_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX31_ZDIR INVISCIDFLUXJACOBIMATRIX31_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX32_ZDIR INVISCIDFLUXJACOBIMATRIX32_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX33_ZDIR INVISCIDFLUXJACOBIMATRIX33_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX34_ZDIR INVISCIDFLUXJACOBIMATRIX34_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX35_ZDIR INVISCIDFLUXJACOBIMATRIX35_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX41_ZDIR INVISCIDFLUXJACOBIMATRIX41_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX42_ZDIR INVISCIDFLUXJACOBIMATRIX42_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX43_ZDIR INVISCIDFLUXJACOBIMATRIX43_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX44_ZDIR INVISCIDFLUXJACOBIMATRIX44_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX45_ZDIR INVISCIDFLUXJACOBIMATRIX45_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX51_ZDIR INVISCIDFLUXJACOBIMATRIX51_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX52_ZDIR INVISCIDFLUXJACOBIMATRIX52_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX53_ZDIR INVISCIDFLUXJACOBIMATRIX53_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX54_ZDIR INVISCIDFLUXJACOBIMATRIX54_ZDIR_3D
#define INVISCIDFLUXJACOBIMATRIX55_ZDIR INVISCIDFLUXJACOBIMATRIX55_ZDIR_3D

#else

#ifdef HYDRO_NDIM
#error "Invalid spatial dimension specified!"
#endif

#endif
#endif
