#ifndef _HYDRO_H_
#define _HYDRO_H_

#if 0
!##############################################################################
!# ****************************************************************************
!# <name> hydro </name>
!# ****************************************************************************
!#
!# <purpose>
!# This is the hydrodynamic header file
!#
!# </purpose>
!##############################################################################
#endif

#include "../../flagship.h"


#if 0
!##############################################################################
! Number of variables
!##############################################################################
#endif

#define NVAR1D 3
#define NVAR2D 4
#define NVAR3D 5


#if 0
!##############################################################################
! Global type of system format
!##############################################################################
#endif

#define SYSTEM_SCALAR 0
#define SYSTEM_BLOCK  1


#if 0
!##############################################################################
! Global type of system coupling approach
!##############################################################################
#endif

#define SYSTEM_SEGREGATED 0
#define SYSTEM_ALLCOUPLED 1


#if 0
!##############################################################################
! Global type of dissipation
!##############################################################################
#endif

#define DISSIPATION_ZERO            0
#define DISSIPATION_SCALAR          1
#define DISSIPATION_ROE             2
#define DISSIPATION_RUSANOV         3
#define DISSIPATION_SCALAR_DSPLIT  -DISSIPATION_SCALAR
#define DISSIPATION_ROE_DSPLIT     -DISSIPATION_ROE
#define DISSIPATION_RUSANOV_DSPLIT -DISSIPATION_RUSANOV


#if 0
!##############################################################################
! Position of variables in vector of conservative variables
!
! By setting HYDRO_VARPOS_EXTERNAL it is possible to define the position of
! the conservative variables externally, e.g., in a larger solution vector.
!##############################################################################
#endif

#ifndef HYDRO_VARPOS_EXTERNAL
#if HYDRO_NDIM == 1

#define _HYDRO_DENSITY_     1
#define _HYDRO_XMOMENTUM_   2
#undef  _HYDRO_YMOMENTUM_
#undef  _HYDRO_ZMOMENTUM_
#define _HYDRO_TOTALENERGY_ 3

#elif HYDRO_NDIM == 2

#define _HYDRO_DENSITY_     1
#define _HYDRO_XMOMENTUM_   2
#define _HYDRO_YMOMENTUM_   3
#undef  _HYDRO_ZMOMENTUM_
#define _HYDRO_TOTALENERGY_ 4

#elif HYDRO_NDIM == 3 || !defined(HYDRO_NDIM)

#define _HYDRO_DENSITY_     1
#define _HYDRO_XMOMENTUM_   2
#define _HYDRO_YMOMENTUM_   3
#define _HYDRO_ZMOMENTUM_   4
#define _HYDRO_TOTALENERGY_ 5

#else

#error "Invalid spatial dimension specified!"

#endif
#endif

#if 0
!##############################################################################
! Conservative variables
!##############################################################################
#endif

#define DENSITY1(U,IDX)                  IDX(U,_HYDRO_DENSITY_)
#define DENSITY2(U,IDX,i,n1,n2)          IDX(U,_HYDRO_DENSITY_,i,n1,n2)
#define DENSITY3(U,IDX,i,j,n1,n2,n3)     IDX(U,_HYDRO_DENSITY_,i,j,n1,n2,n3)

#define XMOMENTUM1(U,IDX)                IDX(U,_HYDRO_XMOMENTUM_)
#define XMOMENTUM2(U,IDX,i,n1,n2)        IDX(U,_HYDRO_XMOMENTUM_,i,n1,n2)
#define XMOMENTUM3(U,IDX,i,j,n1,n2,n3)   IDX(U,_HYDRO_XMOMENTUM_,i,j,n1,n2,n3)

#define YMOMENTUM1(U,IDX)                IDX(U,_HYDRO_YMOMENTUM_)
#define YMOMENTUM2(U,IDX,i,n1,n2)        IDX(U,_HYDRO_YMOMENTUM_,i,n1,n2)
#define YMOMENTUM3(U,IDX,i,j,n1,n2,n3)   IDX(U,_HYDRO_YMOMENTUM_,i,j,n1,n2,n3)

#define ZMOMENTUM1(U,IDX)                IDX(U,_HYDRO_ZMOMENTUM_)
#define ZMOMENTUM2(U,IDX,i,n1,n2)        IDX(U,_HYDRO_ZMOMENTUM_,i,n1,n2)
#define ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)   IDX(U,_HYDRO_ZMOMENTUM_,i,j,n1,n2,n3)

#define TOTALENERGY1(U,IDX)              IDX(U,_HYDRO_TOTALENERGY_)
#define TOTALENERGY2(U,IDX,i,n1,n2)      IDX(U,_HYDRO_TOTALENERGY_,i,n1,n2)
#define TOTALENERGY3(U,IDX,i,j,n1,n2,n3) IDX(U,_HYDRO_TOTALENERGY_,i,j,n1,n2,n3)


#if 0
!##############################################################################
! Roe average values
!##############################################################################
#endif

#define ROE_MEAN_RATIO(ul,ur)       (sqrt(ul/ur))
#define ROE_MEAN_VALUE(ul,ur,ratio) ((ratio*ul+ur)/(ratio+RCONST(1.0)))


#if 0
!##############################################################################
! Include thermodynamic header file
!##############################################################################
#endif

#if 0
! Specify spatial dimension
#endif
#ifdef HYDRO_NDIM
#define THERMODYN_NDIM HYDRO_NDIM
#endif

#if 0
! Specify ratio of specific heats
#endif
#ifdef HYDRO_GAMMA
#define THERMODYN_GAMMA HYDRO_GAMMA
#endif

#include "../../kernel/thermodynamics.h"


#if 0
!##############################################################################
! Fluxes and matrices in 1D
!##############################################################################
#endif

#if 0
! Flux in x-direction for inviscid hydrodynamics in 1D
#endif

#define INVISCIDFLUX1_XDIR1_1D(U,IDX,u,p)  XMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_XDIR1_1D(U,IDX,u,p) (XMOMENTUM1(U,IDX)*u+p)
#define INVISCIDFLUX3_XDIR1_1D(U,IDX,u,p) (TOTALENERGY1(U,IDX)*u+p*u)

#define INVISCIDFLUX1_XDIR2_1D(U,IDX,i,n1,n2,u,p)  XMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_XDIR2_1D(U,IDX,i,n1,n2,u,p) (XMOMENTUM2(U,IDX,i,n1,n2)*u+p)
#define INVISCIDFLUX3_XDIR2_1D(U,IDX,i,n1,n2,u,p) (TOTALENERGY2(U,IDX,i,n1,n2)*u+p*u)

#define INVISCIDFLUX1_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,p)  XMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u+p)
#define INVISCIDFLUX3_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*u+p*u)

#if 0
! Flux Jacobian matrix for inviscid hydrodynamics in 1D
#endif

#define FLUXJACOBIMATRIX11_1D(dscale,CX,u,E) RCONST(0.0)
#define FLUXJACOBIMATRIX12_1D(dscale,CX,u,E) dscale*CX
#define FLUXJACOBIMATRIX13_1D(dscale,CX,u,E) RCONST(0.0)
#define FLUXJACOBIMATRIX21_1D(dscale,CX,u,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(3.0))/RCONST(2.0)*u*u*CX
#define FLUXJACOBIMATRIX22_1D(dscale,CX,u,E) dscale*(RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*u*CX
#define FLUXJACOBIMATRIX23_1D(dscale,CX,u,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CX
#define FLUXJACOBIMATRIX31_1D(dscale,CX,u,E) dscale*(((RCONST(HYDRO_GAMMA))-RCONST(1.0))*u*u-(RCONST(HYDRO_GAMMA))*E)*u*CX
#define FLUXJACOBIMATRIX32_1D(dscale,CX,u,E) dscale*((RCONST(HYDRO_GAMMA))*E-RCONST(3.0)*((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*u*u)*CX
#define FLUXJACOBIMATRIX33_1D(dscale,CX,u,E) dscale*(RCONST(HYDRO_GAMMA))*u*CX

#if 0
! Flux Jacobian matrix in x-direction for inviscid hydrodynamics in 1D
#endif

#define FLUXJACOBIMATRIX11_XDIR_1D(dscale,u,E) FLUXJACOBIMATRIX11_1D(dscale,RCONST(1.0),u,E)
#define FLUXJACOBIMATRIX12_XDIR_1D(dscale,u,E) FLUXJACOBIMATRIX12_1D(dscale,RCONST(1.0),u,E)
#define FLUXJACOBIMATRIX13_XDIR_1D(dscale,u,E) FLUXJACOBIMATRIX13_1D(dscale,RCONST(1.0),u,E)
#define FLUXJACOBIMATRIX21_XDIR_1D(dscale,u,E) FLUXJACOBIMATRIX21_1D(dscale,RCONST(1.0),u,E)
#define FLUXJACOBIMATRIX22_XDIR_1D(dscale,u,E) FLUXJACOBIMATRIX22_1D(dscale,RCONST(1.0),u,E)
#define FLUXJACOBIMATRIX23_XDIR_1D(dscale,u,E) FLUXJACOBIMATRIX23_1D(dscale,RCONST(1.0),u,E)
#define FLUXJACOBIMATRIX31_XDIR_1D(dscale,u,E) FLUXJACOBIMATRIX31_1D(dscale,RCONST(1.0),u,E)
#define FLUXJACOBIMATRIX32_XDIR_1D(dscale,u,E) FLUXJACOBIMATRIX32_1D(dscale,RCONST(1.0),u,E)
#define FLUXJACOBIMATRIX33_XDIR_1D(dscale,u,E) FLUXJACOBIMATRIX33_1D(dscale,RCONST(1.0),u,E)


#if 0
!##############################################################################
! Fluxes and matrices in 2D
!##############################################################################
#endif

#if 0
! Flux in x-direction for inviscid hydrodynamics in 2D
#endif

#define INVISCIDFLUX1_XDIR1_2D(U,IDX,u,p)  XMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_XDIR1_2D(U,IDX,u,p) (XMOMENTUM1(U,IDX)*u+p)
#define INVISCIDFLUX3_XDIR1_2D(U,IDX,u,p) (YMOMENTUM1(U,IDX)*u)
#define INVISCIDFLUX4_XDIR1_2D(U,IDX,u,p) (TOTALENERGY1(U,IDX)*u+p*u)

#define INVISCIDFLUX1_XDIR2_2D(U,IDX,i,n1,n2,u,p)  XMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_XDIR2_2D(U,IDX,i,n1,n2,u,p) (XMOMENTUM2(U,IDX,i,n1,n2)*u+p)
#define INVISCIDFLUX3_XDIR2_2D(U,IDX,i,n1,n2,u,p) (YMOMENTUM2(U,IDX,i,n1,n2)*u)
#define INVISCIDFLUX4_XDIR2_2D(U,IDX,i,n1,n2,u,p) (TOTALENERGY2(U,IDX,i,n1,n2)*u+p*u)

#define INVISCIDFLUX1_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,p)  XMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u+p)
#define INVISCIDFLUX3_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,p) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u)
#define INVISCIDFLUX4_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*u+p*u)

#if 0
! Flux in y-direction for inviscid hydrodynamics in 2D
#endif

#define INVISCIDFLUX1_YDIR1_2D(U,IDX,v,p)  YMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_YDIR1_2D(U,IDX,v,p) (XMOMENTUM1(U,IDX)*v)
#define INVISCIDFLUX3_YDIR1_2D(U,IDX,v,p) (YMOMENTUM1(U,IDX)*v+p)
#define INVISCIDFLUX4_YDIR1_2D(U,IDX,v,p) (TOTALENERGY1(U,IDX)*v+p*v)

#define INVISCIDFLUX1_YDIR2_2D(U,IDX,i,n1,n2,v,p)  YMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_YDIR2_2D(U,IDX,i,n1,n2,v,p) (XMOMENTUM2(U,IDX,i,n1,n2)*v)
#define INVISCIDFLUX3_YDIR2_2D(U,IDX,i,n1,n2,v,p) (YMOMENTUM2(U,IDX,i,n1,n2)*v+p)
#define INVISCIDFLUX4_YDIR2_2D(U,IDX,i,n1,n2,v,p) (TOTALENERGY2(U,IDX,i,n1,n2)*v+p*v)

#define INVISCIDFLUX1_YDIR3_2D(U,IDX,i,j,n1,n2,n3,v,p)  YMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_YDIR3_2D(U,IDX,i,j,n1,n2,n3,v,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v)
#define INVISCIDFLUX3_YDIR3_2D(U,IDX,i,j,n1,n2,n3,v,p) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v+p)
#define INVISCIDFLUX4_YDIR3_2D(U,IDX,i,j,n1,n2,n3,v,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*v+p*v)

#if 0
! Flux Jacobian matrix for inviscid hydrodynamics in 2D
#endif

#define FLUXJACOBIMATRIX11_2D(dscale,CX,CY,u,v,E) RCONST(0.0)
#define FLUXJACOBIMATRIX12_2D(dscale,CX,CY,u,v,E) dscale*CX
#define FLUXJACOBIMATRIX13_2D(dscale,CX,CY,u,v,E) dscale*CY
#define FLUXJACOBIMATRIX14_2D(dscale,CX,CY,u,v,E) RCONST(0.0)
#define FLUXJACOBIMATRIX21_2D(dscale,CX,CY,u,v,E) dscale*((((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(u*u+v*v)-MYNEWLINE u*u)*CX-u*v*CY)
#define FLUXJACOBIMATRIX22_2D(dscale,CX,CY,u,v,E) dscale*((RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*u*CX+v*CY)
#define FLUXJACOBIMATRIX23_2D(dscale,CX,CY,u,v,E) dscale*(u*CY-((RCONST(HYDRO_GAMMA))-RCONST(1.0))*v*CX)
#define FLUXJACOBIMATRIX24_2D(dscale,CX,CY,u,v,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CX
#define FLUXJACOBIMATRIX31_2D(dscale,CX,CY,u,v,E) dscale*((((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(u*u+v*v)-v*v)*CY-MYNEWLINE u*v*CX)
#define FLUXJACOBIMATRIX32_2D(dscale,CX,CY,u,v,E) dscale*(v*CX-((RCONST(HYDRO_GAMMA))-RCONST(1.0))*u*CY)
#define FLUXJACOBIMATRIX33_2D(dscale,CX,CY,u,v,E) dscale*(u*CX+(RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*v*CY)
#define FLUXJACOBIMATRIX34_2D(dscale,CX,CY,u,v,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CY
#define FLUXJACOBIMATRIX41_2D(dscale,CX,CY,u,v,E) dscale*(((RCONST(HYDRO_GAMMA))-RCONST(1.0))*(u*u+v*v)-(RCONST(HYDRO_GAMMA))*E)*(u*CX+v*CY)
#define FLUXJACOBIMATRIX42_2D(dscale,CX,CY,u,v,E) dscale*(((RCONST(HYDRO_GAMMA))*E-((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(u*u+v*v))*CX-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*u*(u*CX+v*CY))
#define FLUXJACOBIMATRIX43_2D(dscale,CX,CY,u,v,E) dscale*(((RCONST(HYDRO_GAMMA))*E-((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(u*u+v*v))*CY-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*v*(u*CX+v*CY))
#define FLUXJACOBIMATRIX44_2D(dscale,CX,CY,u,v,E) dscale*((RCONST(HYDRO_GAMMA))*(u*CX+v*CY))

#if 0
! Flux Jacobian matrix in x-direction for inviscid hydrodynamics in 2D
#endif

#define FLUXJACOBIMATRIX11_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX11_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX12_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX12_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX13_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX13_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX14_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX14_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX21_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX21_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX22_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX22_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX23_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX23_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX24_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX24_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX31_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX31_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX32_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX32_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX33_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX33_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX34_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX34_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX41_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX41_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX42_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX42_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX43_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX43_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)
#define FLUXJACOBIMATRIX44_XDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX44_2D(dscale,RCONST(1.0),RCONST(0.0),u,v,E)

#if 0
! Flux Jacobian matrix in y-direction for inviscid hydrodynamics in 2D
#endif

#define FLUXJACOBIMATRIX11_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX11_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX12_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX12_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX13_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX13_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX14_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX14_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX21_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX21_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX22_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX22_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX23_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX23_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX24_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX24_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX31_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX31_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX32_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX32_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX33_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX33_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX34_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX34_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX41_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX41_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX42_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX42_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX43_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX43_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)
#define FLUXJACOBIMATRIX44_YDIR_2D(dscale,u,v,E) FLUXJACOBIMATRIX44_2D(dscale,RCONST(0.0),RCONST(1.0),u,v,E)


#if 0
!##############################################################################
! Fluxes and matrices in 3D
!##############################################################################
#endif

#if 0
! Flux in x-direction for inviscid hydrodynamics in 3D
#endif

#define INVISCIDFLUX1_XDIR1_3D(U,IDX,u,p)  XMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_XDIR1_3D(U,IDX,u,p) (XMOMENTUM1(U,IDX)*u+p)
#define INVISCIDFLUX3_XDIR1_3D(U,IDX,u,p) (YMOMENTUM1(U,IDX)*u)
#define INVISCIDFLUX4_XDIR1_3D(U,IDX,u,p) (ZMOMENTUM1(U,IDX)*u)
#define INVISCIDFLUX5_XDIR1_3D(U,IDX,u,p) (TOTALENERGY1(U,IDX)*u+p*u)

#define INVISCIDFLUX1_XDIR2_3D(U,IDX,i,n1,n2,u,p)  XMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_XDIR2_3D(U,IDX,i,n1,n2,u,p) (XMOMENTUM2(U,IDX,i,n1,n2)*u+p)
#define INVISCIDFLUX3_XDIR2_3D(U,IDX,i,n1,n2,u,p) (YMOMENTUM2(U,IDX,i,n1,n2)*u)
#define INVISCIDFLUX4_XDIR2_3D(U,IDX,i,n1,n2,u,p) (ZMOMENTUM2(U,IDX,i,n1,n2)*u)
#define INVISCIDFLUX5_XDIR2_3D(U,IDX,i,n1,n2,u,p) (TOTALENERGY2(U,IDX,i,n1,n2)*u+p*u)

#define INVISCIDFLUX1_XDIR3_3D(U,IDX,i,j,n1,n2,n3,u,p)  XMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_XDIR3_3D(U,IDX,i,j,n1,n2,n3,u,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u+p)
#define INVISCIDFLUX3_XDIR3_3D(U,IDX,i,j,n1,n2,n3,u,p) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u)
#define INVISCIDFLUX4_XDIR3_3D(U,IDX,i,j,n1,n2,n3,u,p) (ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u)
#define INVISCIDFLUX5_XDIR3_3D(U,IDX,i,j,n1,n2,n3,u,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*u+p*u)

#if 0
! Flux in y-direction for inviscid hydrodynamics in 3D
#endif

#define INVISCIDFLUX1_YDIR1_3D(U,IDX,v,p)  YMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_YDIR1_3D(U,IDX,v,p) (XMOMENTUM1(U,IDX)*v)
#define INVISCIDFLUX3_YDIR1_3D(U,IDX,v,p) (YMOMENTUM1(U,IDX)*v+p)
#define INVISCIDFLUX4_YDIR1_3D(U,IDX,v,p) (ZMOMENTUM1(U,IDX)*v)
#define INVISCIDFLUX5_YDIR1_3D(U,IDX,v,p) (TOTALENERGY1(U,IDX)*v+p*v)

#define INVISCIDFLUX1_YDIR2_3D(U,IDX,i,n1,n2,v,p)  YMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_YDIR2_3D(U,IDX,i,n1,n2,v,p) (XMOMENTUM2(U,IDX,i,n1,n2)*v)
#define INVISCIDFLUX3_YDIR2_3D(U,IDX,i,n1,n2,v,p) (YMOMENTUM2(U,IDX,i,n1,n2)*v+p)
#define INVISCIDFLUX4_YDIR2_3D(U,IDX,i,n1,n2,v,p) (ZMOMENTUM2(U,IDX,i,n1,n2)*v)
#define INVISCIDFLUX5_YDIR2_3D(U,IDX,i,n1,n2,v,p) (TOTALENERGY2(U,IDX,i,n1,n2)*v+p*v)

#define INVISCIDFLUX1_YDIR3_3D(U,IDX,i,j,n1,n2,n3,v,p)  YMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_YDIR3_3D(U,IDX,i,j,n1,n2,n3,v,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v)
#define INVISCIDFLUX3_YDIR3_3D(U,IDX,i,j,n1,n2,n3,v,p) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v+p)
#define INVISCIDFLUX4_YDIR3_3D(U,IDX,i,j,n1,n2,n3,v,p) (ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v)
#define INVISCIDFLUX5_YDIR3_3D(U,IDX,i,j,n1,n2,n3,v,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*v+p*v)

#if 0
! Flux in z-direction for inviscid hydrodynamics in 3D
#endif

#define INVISCIDFLUX1_ZDIR1_3D(U,IDX,w,p)  ZMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_ZDIR1_3D(U,IDX,w,p) (XMOMENTUM1(U,IDX)*w)
#define INVISCIDFLUX3_ZDIR1_3D(U,IDX,w,p) (YMOMENTUM1(U,IDX)*w)
#define INVISCIDFLUX4_ZDIR1_3D(U,IDX,w,p) (ZMOMENTUM1(U,IDX)*w+p)
#define INVISCIDFLUX5_ZDIR1_3D(U,IDX,w,p) (TOTALENERGY1(U,IDX)*w+p*w)

#define INVISCIDFLUX1_ZDIR2_3D(U,IDX,i,n1,n2,w,p)  ZMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_ZDIR2_3D(U,IDX,i,n1,n2,w,p) (XMOMENTUM2(U,IDX,i,n1,n2)*w)
#define INVISCIDFLUX3_ZDIR2_3D(U,IDX,i,n1,n2,w,p) (YMOMENTUM2(U,IDX,i,n1,n2)*w)
#define INVISCIDFLUX4_ZDIR2_3D(U,IDX,i,n1,n2,w,p) (ZMOMENTUM2(U,IDX,i,n1,n2)*w+p)
#define INVISCIDFLUX5_ZDIR2_3D(U,IDX,i,n1,n2,w,p) (TOTALENERGY2(U,IDX,i,n1,n2)*w+p*w)

#define INVISCIDFLUX1_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,w,p)  ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,w,p) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*w)
#define INVISCIDFLUX3_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,w,p) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*w)
#define INVISCIDFLUX4_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,w,p) (ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)*w+p)
#define INVISCIDFLUX5_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,w,p) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*w+p*w)

#if 0
! Flux Jacobian matrix for inviscid hydrodynamics in 3D
#endif

#define FLUXJACOBIMATRIX11_3D(dscale,CX,CY,CZ,u,v,w,E) RCONST(0.0)
#define FLUXJACOBIMATRIX12_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*CX
#define FLUXJACOBIMATRIX13_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*CY
#define FLUXJACOBIMATRIX14_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*CZ
#define FLUXJACOBIMATRIX15_3D(dscale,CX,CY,CZ,u,v,w,E) RCONST(0.0)
#define FLUXJACOBIMATRIX21_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi)-ui*ui)*CX-MYNEWLINE ui*vi*CY-MYNEWLINE ui*wi*CZ)
#define FLUXJACOBIMATRIX22_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ)
#define FLUXJACOBIMATRIX23_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(ui*CY-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*vi*CX)
#define FLUXJACOBIMATRIX24_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(ui*CZ-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*wi*CX)
#define FLUXJACOBIMATRIX25_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CX
#define FLUXJACOBIMATRIX31_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi)-vi*vi)*CY-MYNEWLINE ui*vi*CX-MYNEWLINE vi*wi*CZ)
#define FLUXJACOBIMATRIX32_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(vi*CX-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*ui*CY)
#define FLUXJACOBIMATRIX33_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*vi*CY+MYNEWLINE ui*CX+MYNEWLINE wi*CZ)
#define FLUXJACOBIMATRIX34_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(vi*CZ-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*wi*CY)
#define FLUXJACOBIMATRIX35_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CY
#define FLUXJACOBIMATRIX41_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi)-wi*wi)*CZ-MYNEWLINE ui*wi*CX-MYNEWLINE vi*wi*CY)
#define FLUXJACOBIMATRIX42_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(wi*CX-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*ui*CZ)
#define FLUXJACOBIMATRIX43_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(wi*CY-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*vi*CZ)
#define FLUXJACOBIMATRIX44_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(3.0)-(RCONST(HYDRO_GAMMA)))*wi*CZ+MYNEWLINE ui*CX+MYNEWLINE vi*CY)
#define FLUXJACOBIMATRIX45_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(HYDRO_GAMMA))-RCONST(1.0))*CZ
#define FLUXJACOBIMATRIX51_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(((RCONST(HYDRO_GAMMA))-RCONST(1.0))*(ui*ui+vi*vi+wi*wi)-MYNEWLINE (RCONST(HYDRO_GAMMA))*Ei)*(ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ)
#define FLUXJACOBIMATRIX52_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(((RCONST(HYDRO_GAMMA))*Ei-((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi))*CX-MYNEWLINE((RCONST(HYDRO_GAMMA))-RCONST(1.0))*ui*(ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ))
#define FLUXJACOBIMATRIX53_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(((RCONST(HYDRO_GAMMA))*Ei-((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi))*CY-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*vi*(ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ))
#define FLUXJACOBIMATRIX54_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*(((RCONST(HYDRO_GAMMA))*Ei-((RCONST(HYDRO_GAMMA))-RCONST(1.0))/RCONST(2.0)*(ui*ui+vi*vi+wi*wi))*CZ-MYNEWLINE ((RCONST(HYDRO_GAMMA))-RCONST(1.0))*wi*(ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ))
#define FLUXJACOBIMATRIX55_3D(dscale,CX,CY,CZ,u,v,w,E) dscale*((RCONST(HYDRO_GAMMA))*(ui*CX+MYNEWLINE vi*CY+MYNEWLINE wi*CZ))

#if 0
! Flux Jacobian matrix in x-direction for inviscid hydrodynamics in 2D
#endif

#define FLUXJACOBIMATRIX11_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX11_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX12_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX12_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX13_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX13_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX14_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX14_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX15_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX15_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX21_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX21_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX22_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX22_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX23_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX23_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX24_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX24_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX25_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX25_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX31_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX31_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX32_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX32_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX33_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX33_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX34_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX34_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX35_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX35_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX41_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX41_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX42_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX42_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX43_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX43_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX44_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX44_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX45_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX45_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX51_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX51_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX52_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX52_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX53_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX53_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX54_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX54_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX55_XDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX55_3D(dscale,RCONST(1.0),RCONST(0.0),RCONST(0.0),u,v,w,E)

#if 0
! Flux Jacobian matrix in y-direction for inviscid hydrodynamics in 2D
#endif

#define FLUXJACOBIMATRIX11_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX11_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX12_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX12_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX13_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX13_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX14_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX14_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX15_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX15_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX21_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX21_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX22_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX22_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX23_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX23_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX24_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX24_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX25_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX25_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX31_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX31_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX32_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX32_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX33_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX33_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX34_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX34_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX35_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX35_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX41_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX41_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX42_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX42_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX43_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX43_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX44_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX44_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX45_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX45_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX51_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX51_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX52_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX52_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX53_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX53_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX54_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX54_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)
#define FLUXJACOBIMATRIX55_YDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX55_3D(dscale,RCONST(0.0),RCONST(1.0),RCONST(0.0),u,v,w,E)

#if 0
! Flux Jacobian matrix in z-direction for inviscid hydrodynamics in 2D
#endif

#define FLUXJACOBIMATRIX11_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX11_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX12_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX12_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX13_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX13_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX14_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX14_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX15_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX15_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX21_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX21_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX22_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX22_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX23_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX23_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX24_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX24_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX25_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX25_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX31_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX31_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX32_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX32_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX33_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX33_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX34_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX34_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX35_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX35_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX41_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX41_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX42_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX42_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX43_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX43_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX44_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX44_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX45_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX45_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX51_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX51_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX52_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX52_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX53_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX53_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX54_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX54_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)
#define FLUXJACOBIMATRIX55_ZDIR_3D(dscale,u,v,w,E) FLUXJACOBIMATRIX55_3D(dscale,RCONST(0.0),RCONST(0.0),RCONST(1.0),u,v,w,E)

#if HYDRO_NDIM == 1

#define INVISCIDFLUX1_XDIR1 INVISCIDFLUX1_XDIR1_1D
#define INVISCIDFLUX2_XDIR1 INVISCIDFLUX2_XDIR1_1D
#define INVISCIDFLUX3_XDIR1 INVISCIDFLUX3_XDIR1_1D

#define INVISCIDFLUX1_XDIR2 INVISCIDFLUX1_XDIR2_1D
#define INVISCIDFLUX2_XDIR2 INVISCIDFLUX2_XDIR2_1D
#define INVISCIDFLUX3_XDIR2 INVISCIDFLUX3_XDIR2_1D

#define INVISCIDFLUX1_XDIR3 INVISCIDFLUX1_XDIR3_1D
#define INVISCIDFLUX2_XDIR3 INVISCIDFLUX2_XDIR3_1D
#define INVISCIDFLUX3_XDIR3 INVISCIDFLUX3_XDIR3_1D

#define FLUXJACOBIMATRIX11 FLUXJACOBIMATRIX11_1D
#define FLUXJACOBIMATRIX12 FLUXJACOBIMATRIX12_1D
#define FLUXJACOBIMATRIX13 FLUXJACOBIMATRIX13_1D
#define FLUXJACOBIMATRIX21 FLUXJACOBIMATRIX21_1D
#define FLUXJACOBIMATRIX22 FLUXJACOBIMATRIX22_1D
#define FLUXJACOBIMATRIX23 FLUXJACOBIMATRIX23_1D
#define FLUXJACOBIMATRIX31 FLUXJACOBIMATRIX31_1D
#define FLUXJACOBIMATRIX32 FLUXJACOBIMATRIX32_1D
#define FLUXJACOBIMATRIX33 FLUXJACOBIMATRIX33_1D

#define FLUXJACOBIMATRIX11_XDIR FLUXJACOBIMATRIX11_XDIR_1D
#define FLUXJACOBIMATRIX12_XDIR FLUXJACOBIMATRIX12_XDIR_1D
#define FLUXJACOBIMATRIX13_XDIR FLUXJACOBIMATRIX13_XDIR_1D
#define FLUXJACOBIMATRIX21_XDIR FLUXJACOBIMATRIX21_XDIR_1D
#define FLUXJACOBIMATRIX22_XDIR FLUXJACOBIMATRIX22_XDIR_1D
#define FLUXJACOBIMATRIX23_XDIR FLUXJACOBIMATRIX23_XDIR_1D
#define FLUXJACOBIMATRIX31_XDIR FLUXJACOBIMATRIX31_XDIR_1D
#define FLUXJACOBIMATRIX32_XDIR FLUXJACOBIMATRIX32_XDIR_1D
#define FLUXJACOBIMATRIX33_XDIR FLUXJACOBIMATRIX33_XDIR_1D

#elif HYDRO_NDIM == 2

#define INVISCIDFLUX1_XDIR1 INVISCIDFLUX1_XDIR1_2D
#define INVISCIDFLUX2_XDIR1 INVISCIDFLUX2_XDIR1_2D
#define INVISCIDFLUX3_XDIR1 INVISCIDFLUX3_XDIR1_2D
#define INVISCIDFLUX4_XDIR1 INVISCIDFLUX4_XDIR1_2D

#define INVISCIDFLUX1_XDIR2 INVISCIDFLUX1_XDIR2_2D
#define INVISCIDFLUX2_XDIR2 INVISCIDFLUX2_XDIR2_2D
#define INVISCIDFLUX3_XDIR2 INVISCIDFLUX3_XDIR2_2D
#define INVISCIDFLUX4_XDIR2 INVISCIDFLUX4_XDIR2_2D

#define INVISCIDFLUX1_XDIR3 INVISCIDFLUX1_XDIR3_2D
#define INVISCIDFLUX2_XDIR3 INVISCIDFLUX2_XDIR3_2D
#define INVISCIDFLUX3_XDIR3 INVISCIDFLUX3_XDIR3_2D
#define INVISCIDFLUX4_XDIR3 INVISCIDFLUX4_XDIR3_2D

#define INVISCIDFLUX1_YDIR1 INVISCIDFLUX1_YDIR1_2D
#define INVISCIDFLUX2_YDIR1 INVISCIDFLUX2_YDIR1_2D
#define INVISCIDFLUX3_YDIR1 INVISCIDFLUX3_YDIR1_2D
#define INVISCIDFLUX4_YDIR1 INVISCIDFLUX4_YDIR1_2D

#define INVISCIDFLUX1_YDIR2 INVISCIDFLUX1_YDIR2_2D
#define INVISCIDFLUX2_YDIR2 INVISCIDFLUX2_YDIR2_2D
#define INVISCIDFLUX3_YDIR2 INVISCIDFLUX3_YDIR2_2D
#define INVISCIDFLUX4_YDIR2 INVISCIDFLUX4_YDIR2_2D

#define INVISCIDFLUX1_YDIR3 INVISCIDFLUX1_YDIR3_2D
#define INVISCIDFLUX2_YDIR3 INVISCIDFLUX2_YDIR3_2D
#define INVISCIDFLUX3_YDIR3 INVISCIDFLUX3_YDIR3_2D
#define INVISCIDFLUX4_YDIR3 INVISCIDFLUX4_YDIR3_2D

#define FLUXJACOBIMATRIX11 FLUXJACOBIMATRIX11_2D
#define FLUXJACOBIMATRIX12 FLUXJACOBIMATRIX12_2D
#define FLUXJACOBIMATRIX13 FLUXJACOBIMATRIX13_2D
#define FLUXJACOBIMATRIX14 FLUXJACOBIMATRIX14_2D
#define FLUXJACOBIMATRIX21 FLUXJACOBIMATRIX21_2D
#define FLUXJACOBIMATRIX22 FLUXJACOBIMATRIX22_2D
#define FLUXJACOBIMATRIX23 FLUXJACOBIMATRIX23_2D
#define FLUXJACOBIMATRIX24 FLUXJACOBIMATRIX24_2D
#define FLUXJACOBIMATRIX31 FLUXJACOBIMATRIX31_2D
#define FLUXJACOBIMATRIX32 FLUXJACOBIMATRIX32_2D
#define FLUXJACOBIMATRIX33 FLUXJACOBIMATRIX33_2D
#define FLUXJACOBIMATRIX34 FLUXJACOBIMATRIX34_2D
#define FLUXJACOBIMATRIX41 FLUXJACOBIMATRIX41_2D
#define FLUXJACOBIMATRIX42 FLUXJACOBIMATRIX42_2D
#define FLUXJACOBIMATRIX43 FLUXJACOBIMATRIX43_2D
#define FLUXJACOBIMATRIX44 FLUXJACOBIMATRIX44_2D

#define FLUXJACOBIMATRIX11_XDIR FLUXJACOBIMATRIX11_XDIR_2D
#define FLUXJACOBIMATRIX12_XDIR FLUXJACOBIMATRIX12_XDIR_2D
#define FLUXJACOBIMATRIX13_XDIR FLUXJACOBIMATRIX13_XDIR_2D
#define FLUXJACOBIMATRIX14_XDIR FLUXJACOBIMATRIX14_XDIR_2D
#define FLUXJACOBIMATRIX21_XDIR FLUXJACOBIMATRIX21_XDIR_2D
#define FLUXJACOBIMATRIX22_XDIR FLUXJACOBIMATRIX22_XDIR_2D
#define FLUXJACOBIMATRIX23_XDIR FLUXJACOBIMATRIX23_XDIR_2D
#define FLUXJACOBIMATRIX24_XDIR FLUXJACOBIMATRIX24_XDIR_2D
#define FLUXJACOBIMATRIX31_XDIR FLUXJACOBIMATRIX31_XDIR_2D
#define FLUXJACOBIMATRIX32_XDIR FLUXJACOBIMATRIX32_XDIR_2D
#define FLUXJACOBIMATRIX33_XDIR FLUXJACOBIMATRIX33_XDIR_2D
#define FLUXJACOBIMATRIX34_XDIR FLUXJACOBIMATRIX34_XDIR_2D
#define FLUXJACOBIMATRIX41_XDIR FLUXJACOBIMATRIX41_XDIR_2D
#define FLUXJACOBIMATRIX42_XDIR FLUXJACOBIMATRIX42_XDIR_2D
#define FLUXJACOBIMATRIX43_XDIR FLUXJACOBIMATRIX43_XDIR_2D
#define FLUXJACOBIMATRIX44_XDIR FLUXJACOBIMATRIX44_XDIR_2D

#define FLUXJACOBIMATRIX11_YDIR FLUXJACOBIMATRIX11_YDIR_2D
#define FLUXJACOBIMATRIX12_YDIR FLUXJACOBIMATRIX12_YDIR_2D
#define FLUXJACOBIMATRIX13_YDIR FLUXJACOBIMATRIX13_YDIR_2D
#define FLUXJACOBIMATRIX14_YDIR FLUXJACOBIMATRIX14_YDIR_2D
#define FLUXJACOBIMATRIX21_YDIR FLUXJACOBIMATRIX21_YDIR_2D
#define FLUXJACOBIMATRIX22_YDIR FLUXJACOBIMATRIX22_YDIR_2D
#define FLUXJACOBIMATRIX23_YDIR FLUXJACOBIMATRIX23_YDIR_2D
#define FLUXJACOBIMATRIX24_YDIR FLUXJACOBIMATRIX24_YDIR_2D
#define FLUXJACOBIMATRIX31_YDIR FLUXJACOBIMATRIX31_YDIR_2D
#define FLUXJACOBIMATRIX32_YDIR FLUXJACOBIMATRIX32_YDIR_2D
#define FLUXJACOBIMATRIX33_YDIR FLUXJACOBIMATRIX33_YDIR_2D
#define FLUXJACOBIMATRIX34_YDIR FLUXJACOBIMATRIX34_YDIR_2D
#define FLUXJACOBIMATRIX41_YDIR FLUXJACOBIMATRIX41_YDIR_2D
#define FLUXJACOBIMATRIX42_YDIR FLUXJACOBIMATRIX42_YDIR_2D
#define FLUXJACOBIMATRIX43_YDIR FLUXJACOBIMATRIX43_YDIR_2D
#define FLUXJACOBIMATRIX44_YDIR FLUXJACOBIMATRIX44_YDIR_2D

#elif HYDRO_NDIM == 3

#define INVISCIDFLUX1_XDIR1 INVISCIDFLUX1_XDIR1_3D
#define INVISCIDFLUX2_XDIR1 INVISCIDFLUX2_XDIR1_3D
#define INVISCIDFLUX3_XDIR1 INVISCIDFLUX3_XDIR1_3D
#define INVISCIDFLUX4_XDIR1 INVISCIDFLUX4_XDIR1_3D
#define INVISCIDFLUX5_XDIR1 INVISCIDFLUX5_XDIR1_3D

#define INVISCIDFLUX1_XDIR2 INVISCIDFLUX1_XDIR2_3D
#define INVISCIDFLUX2_XDIR2 INVISCIDFLUX2_XDIR2_3D
#define INVISCIDFLUX3_XDIR2 INVISCIDFLUX3_XDIR2_3D
#define INVISCIDFLUX4_XDIR2 INVISCIDFLUX4_XDIR2_3D
#define INVISCIDFLUX5_XDIR2 INVISCIDFLUX5_XDIR2_3D

#define INVISCIDFLUX1_XDIR3 INVISCIDFLUX1_XDIR3_3D
#define INVISCIDFLUX2_XDIR3 INVISCIDFLUX2_XDIR3_3D
#define INVISCIDFLUX3_XDIR3 INVISCIDFLUX3_XDIR3_3D
#define INVISCIDFLUX4_XDIR3 INVISCIDFLUX4_XDIR3_3D
#define INVISCIDFLUX5_XDIR3 INVISCIDFLUX5_XDIR3_3D

#define INVISCIDFLUX1_YDIR1 INVISCIDFLUX1_YDIR1_3D
#define INVISCIDFLUX2_YDIR1 INVISCIDFLUX2_YDIR1_3D
#define INVISCIDFLUX3_YDIR1 INVISCIDFLUX3_YDIR1_3D
#define INVISCIDFLUX4_YDIR1 INVISCIDFLUX4_YDIR1_3D
#define INVISCIDFLUX5_YDIR1 INVISCIDFLUX5_YDIR1_3D

#define INVISCIDFLUX1_YDIR2 INVISCIDFLUX1_YDIR2_3D
#define INVISCIDFLUX2_YDIR2 INVISCIDFLUX2_YDIR2_3D
#define INVISCIDFLUX3_YDIR2 INVISCIDFLUX3_YDIR2_3D
#define INVISCIDFLUX4_YDIR2 INVISCIDFLUX4_YDIR2_3D
#define INVISCIDFLUX5_YDIR2 INVISCIDFLUX5_YDIR2_3D

#define INVISCIDFLUX1_YDIR3 INVISCIDFLUX1_YDIR3_3D
#define INVISCIDFLUX2_YDIR3 INVISCIDFLUX2_YDIR3_3D
#define INVISCIDFLUX3_YDIR3 INVISCIDFLUX3_YDIR3_3D
#define INVISCIDFLUX4_YDIR3 INVISCIDFLUX4_YDIR3_3D
#define INVISCIDFLUX5_YDIR3 INVISCIDFLUX5_YDIR3_3D

#define INVISCIDFLUX1_ZDIR1 INVISCIDFLUX1_ZDIR1_3D
#define INVISCIDFLUX2_ZDIR1 INVISCIDFLUX2_ZDIR1_3D
#define INVISCIDFLUX3_ZDIR1 INVISCIDFLUX3_ZDIR1_3D
#define INVISCIDFLUX4_ZDIR1 INVISCIDFLUX4_ZDIR1_3D
#define INVISCIDFLUX5_ZDIR1 INVISCIDFLUX5_ZDIR1_3D

#define INVISCIDFLUX1_ZDIR2 INVISCIDFLUX1_ZDIR2_3D
#define INVISCIDFLUX2_ZDIR2 INVISCIDFLUX2_ZDIR2_3D
#define INVISCIDFLUX3_ZDIR2 INVISCIDFLUX3_ZDIR2_3D
#define INVISCIDFLUX4_ZDIR2 INVISCIDFLUX4_ZDIR2_3D
#define INVISCIDFLUX5_ZDIR2 INVISCIDFLUX5_ZDIR2_3D

#define INVISCIDFLUX1_ZDIR3 INVISCIDFLUX1_ZDIR3_3D
#define INVISCIDFLUX2_ZDIR3 INVISCIDFLUX2_ZDIR3_3D
#define INVISCIDFLUX3_ZDIR3 INVISCIDFLUX3_ZDIR3_3D
#define INVISCIDFLUX4_ZDIR3 INVISCIDFLUX4_ZDIR3_3D
#define INVISCIDFLUX5_ZDIR3 INVISCIDFLUX5_ZDIR3_3D

#define FLUXJACOBIMATRIX11 FLUXJACOBIMATRIX11_3D
#define FLUXJACOBIMATRIX12 FLUXJACOBIMATRIX12_3D
#define FLUXJACOBIMATRIX13 FLUXJACOBIMATRIX13_3D
#define FLUXJACOBIMATRIX14 FLUXJACOBIMATRIX14_3D
#define FLUXJACOBIMATRIX15 FLUXJACOBIMATRIX15_3D
#define FLUXJACOBIMATRIX21 FLUXJACOBIMATRIX21_3D
#define FLUXJACOBIMATRIX22 FLUXJACOBIMATRIX22_3D
#define FLUXJACOBIMATRIX23 FLUXJACOBIMATRIX23_3D
#define FLUXJACOBIMATRIX24 FLUXJACOBIMATRIX24_3D
#define FLUXJACOBIMATRIX25 FLUXJACOBIMATRIX25_3D
#define FLUXJACOBIMATRIX31 FLUXJACOBIMATRIX31_3D
#define FLUXJACOBIMATRIX32 FLUXJACOBIMATRIX32_3D
#define FLUXJACOBIMATRIX33 FLUXJACOBIMATRIX33_3D
#define FLUXJACOBIMATRIX34 FLUXJACOBIMATRIX34_3D
#define FLUXJACOBIMATRIX35 FLUXJACOBIMATRIX35_3D
#define FLUXJACOBIMATRIX41 FLUXJACOBIMATRIX41_3D
#define FLUXJACOBIMATRIX42 FLUXJACOBIMATRIX42_3D
#define FLUXJACOBIMATRIX43 FLUXJACOBIMATRIX43_3D
#define FLUXJACOBIMATRIX44 FLUXJACOBIMATRIX44_3D
#define FLUXJACOBIMATRIX45 FLUXJACOBIMATRIX45_3D
#define FLUXJACOBIMATRIX51 FLUXJACOBIMATRIX51_3D
#define FLUXJACOBIMATRIX52 FLUXJACOBIMATRIX52_3D
#define FLUXJACOBIMATRIX53 FLUXJACOBIMATRIX53_3D
#define FLUXJACOBIMATRIX54 FLUXJACOBIMATRIX54_3D
#define FLUXJACOBIMATRIX55 FLUXJACOBIMATRIX55_3D

#define FLUXJACOBIMATRIX11_XDIR FLUXJACOBIMATRIX11_XDIR_3D
#define FLUXJACOBIMATRIX12_XDIR FLUXJACOBIMATRIX12_XDIR_3D
#define FLUXJACOBIMATRIX13_XDIR FLUXJACOBIMATRIX13_XDIR_3D
#define FLUXJACOBIMATRIX14_XDIR FLUXJACOBIMATRIX14_XDIR_3D
#define FLUXJACOBIMATRIX15_XDIR FLUXJACOBIMATRIX15_XDIR_3D
#define FLUXJACOBIMATRIX21_XDIR FLUXJACOBIMATRIX21_XDIR_3D
#define FLUXJACOBIMATRIX22_XDIR FLUXJACOBIMATRIX22_XDIR_3D
#define FLUXJACOBIMATRIX23_XDIR FLUXJACOBIMATRIX23_XDIR_3D
#define FLUXJACOBIMATRIX24_XDIR FLUXJACOBIMATRIX24_XDIR_3D
#define FLUXJACOBIMATRIX25_XDIR FLUXJACOBIMATRIX25_XDIR_3D
#define FLUXJACOBIMATRIX31_XDIR FLUXJACOBIMATRIX31_XDIR_3D
#define FLUXJACOBIMATRIX32_XDIR FLUXJACOBIMATRIX32_XDIR_3D
#define FLUXJACOBIMATRIX33_XDIR FLUXJACOBIMATRIX33_XDIR_3D
#define FLUXJACOBIMATRIX34_XDIR FLUXJACOBIMATRIX34_XDIR_3D
#define FLUXJACOBIMATRIX35_XDIR FLUXJACOBIMATRIX35_XDIR_3D
#define FLUXJACOBIMATRIX41_XDIR FLUXJACOBIMATRIX41_XDIR_3D
#define FLUXJACOBIMATRIX42_XDIR FLUXJACOBIMATRIX42_XDIR_3D
#define FLUXJACOBIMATRIX43_XDIR FLUXJACOBIMATRIX43_XDIR_3D
#define FLUXJACOBIMATRIX44_XDIR FLUXJACOBIMATRIX44_XDIR_3D
#define FLUXJACOBIMATRIX45_XDIR FLUXJACOBIMATRIX45_XDIR_3D
#define FLUXJACOBIMATRIX51_XDIR FLUXJACOBIMATRIX51_XDIR_3D
#define FLUXJACOBIMATRIX52_XDIR FLUXJACOBIMATRIX52_XDIR_3D
#define FLUXJACOBIMATRIX53_XDIR FLUXJACOBIMATRIX53_XDIR_3D
#define FLUXJACOBIMATRIX54_XDIR FLUXJACOBIMATRIX54_XDIR_3D
#define FLUXJACOBIMATRIX55_XDIR FLUXJACOBIMATRIX55_XDIR_3D

#define FLUXJACOBIMATRIX11_YDIR FLUXJACOBIMATRIX11_YDIR_3D
#define FLUXJACOBIMATRIX12_YDIR FLUXJACOBIMATRIX12_YDIR_3D
#define FLUXJACOBIMATRIX13_YDIR FLUXJACOBIMATRIX13_YDIR_3D
#define FLUXJACOBIMATRIX14_YDIR FLUXJACOBIMATRIX14_YDIR_3D
#define FLUXJACOBIMATRIX15_YDIR FLUXJACOBIMATRIX15_YDIR_3D
#define FLUXJACOBIMATRIX21_YDIR FLUXJACOBIMATRIX21_YDIR_3D
#define FLUXJACOBIMATRIX22_YDIR FLUXJACOBIMATRIX22_YDIR_3D
#define FLUXJACOBIMATRIX23_YDIR FLUXJACOBIMATRIX23_YDIR_3D
#define FLUXJACOBIMATRIX24_YDIR FLUXJACOBIMATRIX24_YDIR_3D
#define FLUXJACOBIMATRIX25_YDIR FLUXJACOBIMATRIX25_YDIR_3D
#define FLUXJACOBIMATRIX31_YDIR FLUXJACOBIMATRIX31_YDIR_3D
#define FLUXJACOBIMATRIX32_YDIR FLUXJACOBIMATRIX32_YDIR_3D
#define FLUXJACOBIMATRIX33_YDIR FLUXJACOBIMATRIX33_YDIR_3D
#define FLUXJACOBIMATRIX34_YDIR FLUXJACOBIMATRIX34_YDIR_3D
#define FLUXJACOBIMATRIX35_YDIR FLUXJACOBIMATRIX35_YDIR_3D
#define FLUXJACOBIMATRIX41_YDIR FLUXJACOBIMATRIX41_YDIR_3D
#define FLUXJACOBIMATRIX42_YDIR FLUXJACOBIMATRIX42_YDIR_3D
#define FLUXJACOBIMATRIX43_YDIR FLUXJACOBIMATRIX43_YDIR_3D
#define FLUXJACOBIMATRIX44_YDIR FLUXJACOBIMATRIX44_YDIR_3D
#define FLUXJACOBIMATRIX45_YDIR FLUXJACOBIMATRIX45_YDIR_3D
#define FLUXJACOBIMATRIX51_YDIR FLUXJACOBIMATRIX51_YDIR_3D
#define FLUXJACOBIMATRIX52_YDIR FLUXJACOBIMATRIX52_YDIR_3D
#define FLUXJACOBIMATRIX53_YDIR FLUXJACOBIMATRIX53_YDIR_3D
#define FLUXJACOBIMATRIX54_YDIR FLUXJACOBIMATRIX54_YDIR_3D
#define FLUXJACOBIMATRIX55_YDIR FLUXJACOBIMATRIX55_YDIR_3D

#define FLUXJACOBIMATRIX11_ZDIR FLUXJACOBIMATRIX11_ZDIR_3D
#define FLUXJACOBIMATRIX12_ZDIR FLUXJACOBIMATRIX12_ZDIR_3D
#define FLUXJACOBIMATRIX13_ZDIR FLUXJACOBIMATRIX13_ZDIR_3D
#define FLUXJACOBIMATRIX14_ZDIR FLUXJACOBIMATRIX14_ZDIR_3D
#define FLUXJACOBIMATRIX15_ZDIR FLUXJACOBIMATRIX15_ZDIR_3D
#define FLUXJACOBIMATRIX21_ZDIR FLUXJACOBIMATRIX21_ZDIR_3D
#define FLUXJACOBIMATRIX22_ZDIR FLUXJACOBIMATRIX22_ZDIR_3D
#define FLUXJACOBIMATRIX23_ZDIR FLUXJACOBIMATRIX23_ZDIR_3D
#define FLUXJACOBIMATRIX24_ZDIR FLUXJACOBIMATRIX24_ZDIR_3D
#define FLUXJACOBIMATRIX25_ZDIR FLUXJACOBIMATRIX25_ZDIR_3D
#define FLUXJACOBIMATRIX31_ZDIR FLUXJACOBIMATRIX31_ZDIR_3D
#define FLUXJACOBIMATRIX32_ZDIR FLUXJACOBIMATRIX32_ZDIR_3D
#define FLUXJACOBIMATRIX33_ZDIR FLUXJACOBIMATRIX33_ZDIR_3D
#define FLUXJACOBIMATRIX34_ZDIR FLUXJACOBIMATRIX34_ZDIR_3D
#define FLUXJACOBIMATRIX35_ZDIR FLUXJACOBIMATRIX35_ZDIR_3D
#define FLUXJACOBIMATRIX41_ZDIR FLUXJACOBIMATRIX41_ZDIR_3D
#define FLUXJACOBIMATRIX42_ZDIR FLUXJACOBIMATRIX42_ZDIR_3D
#define FLUXJACOBIMATRIX43_ZDIR FLUXJACOBIMATRIX43_ZDIR_3D
#define FLUXJACOBIMATRIX44_ZDIR FLUXJACOBIMATRIX44_ZDIR_3D
#define FLUXJACOBIMATRIX45_ZDIR FLUXJACOBIMATRIX45_ZDIR_3D
#define FLUXJACOBIMATRIX51_ZDIR FLUXJACOBIMATRIX51_ZDIR_3D
#define FLUXJACOBIMATRIX52_ZDIR FLUXJACOBIMATRIX52_ZDIR_3D
#define FLUXJACOBIMATRIX53_ZDIR FLUXJACOBIMATRIX53_ZDIR_3D
#define FLUXJACOBIMATRIX54_ZDIR FLUXJACOBIMATRIX54_ZDIR_3D
#define FLUXJACOBIMATRIX55_ZDIR FLUXJACOBIMATRIX55_ZDIR_3D

#else

#ifdef HYDRO_NDIM
#error "Invalid spatial dimension specified!"
#endif

#endif
#endif
