#!/usr/bin/env gmake

FEATFLOW=../..

include $(FEATFLOW)/Globals.mk

LIBNAME=umfpack2

SRCLIST= umd21i.f umd2co.f umd2er.f umd2f0.f umd2f1.f umd2f2.f \
  umd2fa.f umd2fb.f umd2fg.f umd2in.f umd2lt.f umd2of.f \
  umd2p1.f umd2p2.f umd2r0.f umd2r2.f umd2ra.f umd2rf.f \
  umd2rg.f umd2s2.f umd2sl.f umd2so.f umd2su.f umd2ut.f \
  ums21i.f ums2co.f ums2er.f ums2f0.f ums2f1.f ums2f2.f \
  ums2fa.f ums2fb.f ums2fg.f ums2in.f ums2lt.f ums2of.f \
  ums2p1.f ums2p2.f ums2r0.f ums2r2.f ums2ra.f ums2rf.f \
  ums2rg.f ums2s2.f ums2sl.f ums2so.f ums2su.f ums2ut.f \
  umc21i.f umc2co.f umc2er.f umc2f0.f umc2f1.f umc2f2.f \
  umc2fa.f umc2fb.f umc2fg.f umc2in.f umc2of.f umc2p1.f \
  umc2p2.f umc2r0.f umc2r2.f umc2ra.f umc2rf.f umc2rg.f \
  umc2s2.f umc2sl.f umc2so.f umc2su.f umz21i.f umz2co.f \
  umz2er.f umz2f0.f umz2f1.f umz2f2.f umz2fa.f umz2fb.f \
  umz2fg.f umz2in.f umz2of.f umz2p1.f umz2p2.f umz2r0.f \
  umz2r2.f umz2ra.f umz2rf.f umz2rg.f umz2s2.f umz2sl.f \
  umz2so.f umz2su.f mc21b.f mc13e.f

include $(FEATFLOW)/Rules_libs.mk
