#!/usr/bin/env gmake

FEATFLOW=../..

include $(FEATFLOW)/Globals.mk

LIBNAME=zlib

INCDIR= -I./include -I./src

SRCLIST= adler32.c compress.c crc32.c gzio.c uncompr.c deflate.c trees.c \
	zutil.c inflate.c infback.c inftrees.c inffast.c

include $(FEATFLOW)/Rules_libs.mk
