
c**********************************************************************
c                   SPLIB Copyright (C) 1995                         **
c                     Indiana University                             **
c**********************************************************************

      common /instvars/ times,ipcprm,solver,precond
      character solver*5, precond*4
      integer ipcprm
      real*8 times(20)
