
c**********************************************************************
c                   SPLIB Copyright (C) 1995                         **
c                     Indiana University                             **
c**********************************************************************

      common /spksys/ iprnte, iprnts, maxint, ratios, ratio1,
     1                mcheps, time
c      common /spausr/ msglva, ierra, neqns
      common /spausr/ msglva, ierra
      integer msglva, ierra, maxsa, neqns
      integer iprnte, iprnts, maxint
      real            ratios, ratio1, mcheps, time
