

#ifndef _MHD_H_
#define _MHD_H_

#if 0
!##############################################################################
!# ****************************************************************************
!# <name> mhd </name>
!# ****************************************************************************
!#
!# <purpose>
!# This is the magnetohydrodynamic header file
!#
!# </purpose>
!##############################################################################
#endif


#include "../../flagship.h"
#include "../../../../../kernel/System/idxmanager.h"


#if 0
!##############################################################################
! Number of variables
!##############################################################################
#endif

#define NVAR1D 7
#define NVAR2D 8
#define NVAR3D 8


#if 0
!##############################################################################
! Global type of system format
!##############################################################################
#endif

#define SYSTEM_SCALAR 0
#define SYSTEM_BLOCK  1


#if 0
!##############################################################################
! Global type of system coupling approach
!##############################################################################
#endif

#define SYSTEM_SEGREGATED 0
#define SYSTEM_ALLCOUPLED 1


#if 0
!##############################################################################
! Global type of dissipation
!##############################################################################
#endif

#define DISSIPATION_ZERO            0
#define DISSIPATION_SCALAR          1
#define DISSIPATION_ROE             2
#define DISSIPATION_RUSANOV         3
#define DISSIPATION_SCALAR_DSPLIT  -DISSIPATION_SCALAR
#define DISSIPATION_ROE_DSPLIT     -DISSIPATION_ROE
#define DISSIPATION_RUSANOV_DSPLIT -DISSIPATION_RUSANOV


#if 0
!##############################################################################
! Position of variables in vector of conservative variables
!
! By setting MHD_VARPOS_EXTERNAL it is possible to define the position of
! the conservative variables externally, e.g., in a larger solution vector.
!##############################################################################
#endif

#ifndef MHD_VARPOS_EXTERNAL
#if MHD_NDIM == 1

#define _MHD_DENSITY_     1
#define _MHD_XMOMENTUM_   2
#define _MHD_YMOMENTUM_   3
#define _MHD_ZMOMENTUM_   4
#undef  _MHD_XMAGFIELD_
#define _MHD_YMAGFIELD_   5
#define _MHD_ZMAGFIELD_   6
#define _MHD_TOTALENERGY_ 7

#elif MHD_NDIM == 2 || MHD_NDIM == 3 || !defined(MHD_NDIM)

#define _MHD_DENSITY_     1
#define _MHD_XMOMENTUM_   2
#define _MHD_YMOMENTUM_   3
#define _MHD_ZMOMENTUM_   4
#define _MHD_XMAGFIELD_   5
#define _MHD_YMAGFIELD_   6
#define _MHD_ZMAGFIELD_   7
#define _MHD_TOTALENERGY_ 8

#else

#error "Invalid spatial dimension specified!"

#endif
#endif


#if 0
! In one dimension, the x-component of the magnetic field is constant.
#endif
#ifndef MHD_XMAGFIELD_CONST
#define MHD_XMAGFIELD_CONST 1.0
#endif


#if 0
!##############################################################################
! Conservative variables
!##############################################################################
#endif

#define DENSITY1(U,IDX)                  IDX(U,_MHD_DENSITY_)
#define DENSITY2(U,IDX,i,n1,n2)          IDX(U,_MHD_DENSITY_,i,n1,n2)
#define DENSITY3(U,IDX,i,j,n1,n2,n3)     IDX(U,_MHD_DENSITY_,i,j,n1,n2,n3)

#define XMOMENTUM1(U,IDX)                IDX(U,_MHD_XMOMENTUM_)
#define XMOMENTUM2(U,IDX,i,n1,n2)        IDX(U,_MHD_XMOMENTUM_,i,n1,n2)
#define XMOMENTUM3(U,IDX,i,j,n1,n2,n3)   IDX(U,_MHD_XMOMENTUM_,i,j,n1,n2,n3)

#define YMOMENTUM1(U,IDX)                IDX(U,_MHD_YMOMENTUM_)
#define YMOMENTUM2(U,IDX,i,n1,n2)        IDX(U,_MHD_YMOMENTUM_,i,n1,n2)
#define YMOMENTUM3(U,IDX,i,j,n1,n2,n3)   IDX(U,_MHD_YMOMENTUM_,i,j,n1,n2,n3)

#define ZMOMENTUM1(U,IDX)                IDX(U,_MHD_ZMOMENTUM_)
#define ZMOMENTUM2(U,IDX,i,n1,n2)        IDX(U,_MHD_ZMOMENTUM_,i,n1,n2)
#define ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)   IDX(U,_MHD_ZMOMENTUM_,i,j,n1,n2,n3)

#if MHD_NDIM == 1

#define XMAGFIELD1(U,IDX)                (RCONST(MHD_XMAGFIELD_CONST))
#define XMAGFIELD2(U,IDX,i,n1,n2)        (RCONST(MHD_XMAGFIELD_CONST))
#define XMAGFIELD3(U,IDX,i,j,n1,n2,n3)   (RCONST(MHD_XMAGFIELD_CONST))

#elif MHD_NDIM == 2 || MHD_NDIM == 3 || !defined(MHD_NDIM)

#define XMAGFIELD1(U,IDX)                IDX(U,_MHD_XMAGFIELD_)
#define XMAGFIELD2(U,IDX,i,n1,n2)        IDX(U,_MHD_XMAGFIELD_,i,n1,n2)
#define XMAGFIELD3(U,IDX,i,j,n1,n2,n3)   IDX(U,_MHD_XMAGFIELD_,i,j,n1,n2,n3)

#else

#error "Invalid spatial dimension specified!"

#endif

#define YMAGFIELD1(U,IDX)                IDX(U,_MHD_YMAGFIELD_)
#define YMAGFIELD2(U,IDX,i,n1,n2)        IDX(U,_MHD_YMAGFIELD_,i,n1,n2)
#define YMAGFIELD3(U,IDX,i,j,n1,n2,n3)   IDX(U,_MHD_YMAGFIELD_,i,j,n1,n2,n3)

#define ZMAGFIELD1(U,IDX)                IDX(U,_MHD_ZMAGFIELD_)
#define ZMAGFIELD2(U,IDX,i,n1,n2)        IDX(U,_MHD_ZMAGFIELD_,i,n1,n2)
#define ZMAGFIELD3(U,IDX,i,j,n1,n2,n3)   IDX(U,_MHD_ZMAGFIELD_,i,j,n1,n2,n3)

#define TOTALENERGY1(U,IDX)              IDX(U,_MHD_TOTALENERGY_)
#define TOTALENERGY2(U,IDX,i,n1,n2)      IDX(U,_MHD_TOTALENERGY_,i,n1,n2)
#define TOTALENERGY3(U,IDX,i,j,n1,n2,n3) IDX(U,_MHD_TOTALENERGY_,i,j,n1,n2,n3)


#if 0
!##############################################################################
! Roe average values
!##############################################################################
#endif

#define ROE_MEAN_RATIO(ul,ur)       (sqrt(ul/ur))
#define ROE_MEAN_VALUE(ul,ur,ratio) ((ratio*ul+MYNEWLINE ur)/MYNEWLINE (ratio+RCONST(1.0)))


#if 0
!##############################################################################
! Auxiliary quantities
!##############################################################################
#endif

#define MAG_DOT_VEL1(U,IDX,u,v,w)              (XMAGFIELD1(U,IDX)*u+ MYNEWLINE YMAGFIELD1(U,IDX)*v+ MYNEWLINE ZMAGFIELD1(U,IDX)*w)
#define MAG_DOT_VEL2(U,IDX,i,n1,n2,u,v,w)      (XMAGFIELD2(U,IDX,i,n1,n2)*u+ MYNEWLINE YMAGFIELD2(U,IDX,i,n1,n2)*v+ MYNEWLINE ZMAGFIELD2(U,IDX,i,n1,n2)*w)
#define MAG_DOT_VEL3(U,IDX,i,j,n1,n2,n3,u,v,w) (XMAGFIELD3(U,IDX,i,j,n1,n2,n3)*u+ MYNEWLINE YMAGFIELD3(U,IDX,i,j,n1,n2,n3)*v+ MYNEWLINE ZMAGFIELD3(U,IDX,i,j,n1,n2,n3)*w)


#if 0
!##############################################################################
! Include magnetohydrodynamic header file
!##############################################################################
#endif

#if 0
! Specify spatial dimension
#endif
#ifdef MHD_NDIM
#define MAGNETOHYDRODYN_NDIM MHD_NDIM
#endif

#if 0
! Specify ratio of specific heats
#endif
#ifdef MHD_GAMMA
#define MAGNETOHYDRODYN_GAMMA MHD_GAMMA
#endif

#if 0
! Specify Vacuum permittivity
#endif
#ifdef MHD_VACUUM_PERM
#define MAGNETOHYDRODYN_VACUUM_PERM MHD_VACUUM_PERM
#endif

#include "../../kernel/magnetohydrodynamics.h"


#if 0
!##############################################################################
! Fluxes and matrices in 1D
!##############################################################################
#endif

#if 0
! Flux in x-direction for ideal MHD in 1D
#endif

#define INVISCIDFLUX1_XDIR1_1D(U,IDX,u,v,w,p,q)  XMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_XDIR1_1D(U,IDX,u,v,w,p,q) (XMOMENTUM1(U,IDX)*u+p)
#define INVISCIDFLUX3_XDIR1_1D(U,IDX,u,v,w,p,q) (YMOMENTUM1(U,IDX)*u-MYNEWLINE XMAGFIELD1(U,IDX)* MYNEWLINE YMAGFIELD(U,IDX))
#define INVISCIDFLUX4_XDIR1_1D(U,IDX,u,v,w,p,q) (ZMOMENTUM1(U,IDX)*u-MYNEWLINE XMAGFIELD1(U,IDX)* MYNEWLINE ZMAGFIELD1(U,IDX))
#define INVISCIDFLUX5_XDIR1_1D(U,IDX,u,v,w,p,q) (YMAGFIELD1(U,IDX)*u-MYNEWLINE XMAGFIELD1(U,IDX)*v)
#define INVISCIDFLUX6_XDIR1_1D(U,IDX,u,v,w,p,q) (ZMAGFIELD1(U,IDX)*u-MYNEWLINE XMAGFIELD1(U,IDX)*w)
#define INVISCIDFLUX7_XDIR1_1D(U,IDX,u,v,w,p,q) (TOTALENERGY1(U,IDX)*u+p*u-MYNEWLINE XMAGFIELD1(U,IDX)*q)

#define INVISCIDFLUX1_XDIR2_1D(U,IDX,i,n1,n2,u,v,w,p,q)  XMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_XDIR2_1D(U,IDX,i,n1,n2,u,v,w,p,q) (XMOMENTUM2(U,IDX,i,n1,n2)*u+p)
#define INVISCIDFLUX3_XDIR2_1D(U,IDX,i,n1,n2,u,v,w,p,q) (YMOMENTUM2(U,IDX,i,n1,n2)*u-MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2)* MYNEWLINE YMAGFIELD2(U,IDX,i,n1,n2))
#define INVISCIDFLUX4_XDIR2_1D(U,IDX,i,n1,n2,u,v,w,p,q) (ZMOMENTUM2(U,IDX,i,n1,n2)*u-MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2)* MYNEWLINE ZMAGFIELD2(U,IDX,i,n1,n2))
#define INVISCIDFLUX5_XDIR2_1D(U,IDX,i,n1,n2,u,v,w,p,q) (YMAGFIELD2(U,IDX,i,n1,n2)*u-MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2)*v)
#define INVISCIDFLUX6_XDIR2_1D(U,IDX,i,n1,n2,u,v,w,p,q) (ZMAGFIELD2(U,IDX,i,n1,n2)*u-MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2)*w)
#define INVISCIDFLUX7_XDIR2_1D(U,IDX,i,n1,n2,u,v,w,p,q) (TOTALENERGY2(U,IDX,i,n1,n2)*u+p*u-MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2)*q)

#define INVISCIDFLUX1_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q)  XMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u+p)
#define INVISCIDFLUX3_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u-MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3)* MYNEWLINE YMAGFIELD3(U,IDX,i,j,n1,n2,n3))
#define INVISCIDFLUX4_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u-MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3)* MYNEWLINE ZMAGFIELD3(U,IDX,i,j,n1,n2,n3))
#define INVISCIDFLUX5_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (YMAGFIELD3(U,IDX,i,j,n1,n2,n3)*u-MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3)*v)
#define INVISCIDFLUX6_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (ZMAGFIELD3(U,IDX,i,j,n1,n2,n3)*u-MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3)*w)
#define INVISCIDFLUX7_XDIR3_1D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*u+p*u-MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3)*q)

#if 0
! Flux Jacobian matrix for ideal MHD in 1D
#endif

#if 0
! Flux Jacobian matrix in x-direction for ideal MHD in 1D
#endif


#if 0
!##############################################################################
! Fluxes and matrices in 2D
!##############################################################################
#endif

#if 0
! Flux in x-direction for ideal MHD in 2D
#endif

#define INVISCIDFLUX1_XDIR1_2D(U,IDX,u,v,w,p,q)  XMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_XDIR1_2D(U,IDX,u,v,w,p,q) (XMOMENTUM1(U,IDX)*u+p-MYNEWLINE POW(XMAGFIELD1(U,IDX),2))
#define INVISCIDFLUX3_XDIR1_2D(U,IDX,u,v,w,p,q) (YMOMENTUM1(U,IDX)*u-MYNEWLINE XMAGFIELD1(U,IDX)* MYNEWLINE YMAGFIELD1(U,IDX))
#define INVISCIDFLUX4_XDIR1_2D(U,IDX,u,v,w,p,q) (ZMOMENTUM1(U,IDX)*u-MYNEWLINE XMAGFIELD1(U,IDX)* MYNEWLINE ZMAGFIELD1(U,IDX))
#define INVISCIDFLUX5_XDIR1_2D(U,IDX,u,v,w,p,q)  RCONST(0.0)
#define INVISCIDFLUX6_XDIR1_2D(U,IDX,u,v,w,p,q) (YMAGFIELD1(U,IDX)*u-MYNEWLINE XMAGFIELD1(U,IDX)*v)
#define INVISCIDFLUX7_XDIR1_2D(U,IDX,u,v,w,p,q) (ZMAGFIELD1(U,IDX)*u-MYNEWLINE XMAGFIELD1(U,IDX)*w)
#define INVISCIDFLUX8_XDIR1_2D(U,IDX,u,v,w,p,q) (TOTALENERGY1(U,IDX)*u+p*u-MYNEWLINE XMAGFIELD1(U,IDX)*q)

#define INVISCIDFLUX1_XDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q)  XMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_XDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (XMOMENTUM2(U,IDX,i,n1,n2)*u+p-MYNEWLINE POW(XMAGFIELD2(U,IDX,i,n1,n2),2))
#define INVISCIDFLUX3_XDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (YMOMENTUM2(U,IDX,i,n1,n2)*u-MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2)* MYNEWLINE YMAGFIELD2(U,IDX,i,n1,n2))
#define INVISCIDFLUX4_XDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (ZMOMENTUM2(U,IDX,i,n1,n2)*u-MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2)* MYNEWLINE ZMAGFIELD2(U,IDX,i,n1,n2))
#define INVISCIDFLUX5_XDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q)  RCONST(0.0)
#define INVISCIDFLUX6_XDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (YMAGFIELD2(U,IDX,i,n1,n2)*u-MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2)*v)
#define INVISCIDFLUX7_XDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (ZMAGFIELD2(U,IDX,i,n1,n2)*u-MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2)*w)
#define INVISCIDFLUX8_XDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (TOTALENERGY2(U,IDX,i,n1,n2)*u+p*u-MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2)*q)

#define INVISCIDFLUX1_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q)  XMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u+p-MYNEWLINE POW(XMAGFIELD3(U,IDX,i,j,n1,n2,n3),2))
#define INVISCIDFLUX3_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u-MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3)* MYNEWLINE YMAGFIELD3(U,IDX,i,j,n1,n2,n3))
#define INVISCIDFLUX4_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)*u-MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3)* MYNEWLINE ZMAGFIELD3(U,IDX,i,j,n1,n2,n3))
#define INVISCIDFLUX5_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q)  RCONST(0.0)
#define INVISCIDFLUX6_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (YMAGFIELD3(U,IDX,i,j,n1,n2,n3)*u-MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3)*v)
#define INVISCIDFLUX7_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (ZMAGFIELD3(U,IDX,i,j,n1,n2,n3)*u-MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3)*w)
#define INVISCIDFLUX8_XDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*u+p*u-MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3)*q)


#if 0
! Flux in y-direction for ideal MHD in 2D
#endif

#define INVISCIDFLUX1_YDIR1_2D(U,IDX,u,v,w,p,q)  YMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_YDIR1_2D(U,IDX,u,v,w,p,q) (XMOMENTUM1(U,IDX)*v-MYNEWLINE YMAGFIELD1(U,IDX)* MYNEWLINE XMAGFIELD1(U,IDX))
#define INVISCIDFLUX3_YDIR1_2D(U,IDX,u,v,w,p,q) (YMOMENTUM1(U,IDX)*v+p-MYNEWLINE POW(YMAGFIELD1(U,IDX),2))
#define INVISCIDFLUX4_YDIR1_2D(U,IDX,u,v,w,p,q) (ZMOMENTUM1(U,IDX)*v-MYNEWLINE YMAGFIELD1(U,IDX)* MYNEWLINE ZMAGFIELD1(U,IDX))
#define INVISCIDFLUX5_YDIR1_2D(U,IDX,u,v,w,p,q) (XMAGFIELD1(U,IDX)*v-MYNEWLINE YMAGFIELD1(U,IDX)*u)
#define INVISCIDFLUX6_YDIR1_2D(U,IDX,u,v,w,p,q)  RCONST(0.0)
#define INVISCIDFLUX7_YDIR1_2D(U,IDX,u,v,w,p,q) (ZMAGFIELD1(U,IDX)*v-MYNEWLINE YMAGFIELD1(U,IDX)*w)
#define INVISCIDFLUX8_YDIR1_2D(U,IDX,u,v,w,p,q) (TOTALENERGY1(U,IDX)*v+p*v-MYNEWLINE YMAGFIELD1(U,IDX)*q)

#define INVISCIDFLUX1_YDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q)  YMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_YDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (XMOMENTUM2(U,IDX,i,n1,n2)*v-MYNEWLINE YMAGFIELD2(U,IDX,i,n1,n2)* MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2))
#define INVISCIDFLUX3_YDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (YMOMENTUM2(U,IDX,i,n1,n2)*v+p-MYNEWLINE POW(YMAGFIELD2(U,IDX,i,n1,n2),2))
#define INVISCIDFLUX4_YDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (ZMOMENTUM2(U,IDX,i,n1,n2)*v-MYNEWLINE YMAGFIELD2(U,IDX,i,n1,n2)* MYNEWLINE ZMAGFIELD2(U,IDX,i,n1,n2))
#define INVISCIDFLUX5_YDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (XMAGFIELD2(U,IDX,i,n1,n2)*v-MYNEWLINE YMAGFIELD2(U,IDX,i,n1,n2)*u)
#define INVISCIDFLUX6_YDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q)  RCONST(0.0)
#define INVISCIDFLUX7_YDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (ZMAGFIELD2(U,IDX,i,n1,n2)*v-MYNEWLINE YMAGFIELD2(U,IDX,i,n1,n2)*w)
#define INVISCIDFLUX8_YDIR2_2D(U,IDX,i,n1,n2,u,v,w,p,q) (TOTALENERGY2(U,IDX,i,n1,n2)*v+p*v-MYNEWLINE YMAGFIELD2(U,IDX,i,n1,n2)*q)

#define INVISCIDFLUX1_YDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q)  YMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_YDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v-MYNEWLINE YMAGFIELD3(U,IDX,i,j,n1,n2,n3)* MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3))
#define INVISCIDFLUX3_YDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v+p-MYNEWLINE POW(YMAGFIELD3(U,IDX,i,j,n1,n2,n3),2))
#define INVISCIDFLUX4_YDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)*v-MYNEWLINE YMAGFIELD3(U,IDX,i,j,n1,n2,n3)* MYNEWLINE ZMAGFIELD3(U,IDX,i,j,n1,n2,n3))
#define INVISCIDFLUX5_YDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (XMAGFIELD3(U,IDX,i,j,n1,n2,n3)*v-MYNEWLINE YMAGFIELD3(U,IDX,i,j,n1,n2,n3)*u)
#define INVISCIDFLUX6_YDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q)  RCONST(0.0)
#define INVISCIDFLUX7_YDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (ZMAGFIELD3(U,IDX,i,j,n1,n2,n3)*v-MYNEWLINE YMAGFIELD3(U,IDX,i,j,n1,n2,n3)*w)
#define INVISCIDFLUX8_YDIR3_2D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*v+p*v-MYNEWLINE YMAGFIELD3(U,IDX,i,j,n1,n2,n3)*q)


#if 0
!##############################################################################
! Fluxes and matrices in 3D
!##############################################################################
#endif

#if 0
  ! Flux in x-direction for ideal MHD in 3D (same as in 2D)
#endif

#define INVISCIDFLUX1_XDIR1_3D INVISCIDFLUX1_XDIR1_2D
#define INVISCIDFLUX2_XDIR1_3D INVISCIDFLUX2_XDIR1_2D
#define INVISCIDFLUX3_XDIR1_3D INVISCIDFLUX3_XDIR1_2D
#define INVISCIDFLUX4_XDIR1_3D INVISCIDFLUX4_XDIR1_2D
#define INVISCIDFLUX5_XDIR1_3D INVISCIDFLUX5_XDIR1_2D
#define INVISCIDFLUX6_XDIR1_3D INVISCIDFLUX6_XDIR1_2D
#define INVISCIDFLUX7_XDIR1_3D INVISCIDFLUX7_XDIR1_2D
#define INVISCIDFLUX8_XDIR1_3D INVISCIDFLUX8_XDIR1_2D

#define INVISCIDFLUX1_XDIR2_3D INVISCIDFLUX1_XDIR2_2D
#define INVISCIDFLUX2_XDIR2_3D INVISCIDFLUX2_XDIR2_2D
#define INVISCIDFLUX3_XDIR2_3D INVISCIDFLUX3_XDIR2_2D
#define INVISCIDFLUX4_XDIR2_3D INVISCIDFLUX4_XDIR2_2D
#define INVISCIDFLUX5_XDIR2_3D INVISCIDFLUX5_XDIR2_2D
#define INVISCIDFLUX6_XDIR2_3D INVISCIDFLUX6_XDIR2_2D
#define INVISCIDFLUX7_XDIR2_3D INVISCIDFLUX7_XDIR2_2D
#define INVISCIDFLUX8_XDIR2_3D INVISCIDFLUX8_XDIR2_2D

#define INVISCIDFLUX1_XDIR3_3D INVISCIDFLUX1_XDIR3_2D
#define INVISCIDFLUX2_XDIR3_3D INVISCIDFLUX2_XDIR3_2D
#define INVISCIDFLUX3_XDIR3_3D INVISCIDFLUX3_XDIR3_2D
#define INVISCIDFLUX4_XDIR3_3D INVISCIDFLUX4_XDIR3_2D
#define INVISCIDFLUX5_XDIR3_3D INVISCIDFLUX5_XDIR3_2D
#define INVISCIDFLUX6_XDIR3_3D INVISCIDFLUX6_XDIR3_2D
#define INVISCIDFLUX7_XDIR3_3D INVISCIDFLUX7_XDIR3_2D
#define INVISCIDFLUX8_XDIR3_3D INVISCIDFLUX8_XDIR3_2D

#if 0
  ! Flux in y-direction for ideal MHD in 3D (same as in 2D)
#endif

#define INVISCIDFLUX1_YDIR1_3D INVISCIDFLUX1_YDIR1_2D
#define INVISCIDFLUX2_YDIR1_3D INVISCIDFLUX2_YDIR1_2D
#define INVISCIDFLUX3_YDIR1_3D INVISCIDFLUX3_YDIR1_2D
#define INVISCIDFLUX4_YDIR1_3D INVISCIDFLUX4_YDIR1_2D
#define INVISCIDFLUX5_YDIR1_3D INVISCIDFLUX5_YDIR1_2D
#define INVISCIDFLUX6_YDIR1_3D INVISCIDFLUX6_YDIR1_2D
#define INVISCIDFLUX7_YDIR1_3D INVISCIDFLUX7_YDIR1_2D
#define INVISCIDFLUX8_YDIR1_3D INVISCIDFLUX8_YDIR1_2D

#define INVISCIDFLUX1_YDIR2_3D INVISCIDFLUX1_YDIR2_2D
#define INVISCIDFLUX2_YDIR2_3D INVISCIDFLUX2_YDIR2_2D
#define INVISCIDFLUX3_YDIR2_3D INVISCIDFLUX3_YDIR2_2D
#define INVISCIDFLUX4_YDIR2_3D INVISCIDFLUX4_YDIR2_2D
#define INVISCIDFLUX5_YDIR2_3D INVISCIDFLUX5_YDIR2_2D
#define INVISCIDFLUX6_YDIR2_3D INVISCIDFLUX6_YDIR2_2D
#define INVISCIDFLUX7_YDIR2_3D INVISCIDFLUX7_YDIR2_2D
#define INVISCIDFLUX8_YDIR2_3D INVISCIDFLUX8_YDIR2_2D

#define INVISCIDFLUX1_YDIR3_3D INVISCIDFLUX1_YDIR3_2D
#define INVISCIDFLUX2_YDIR3_3D INVISCIDFLUX2_YDIR3_2D
#define INVISCIDFLUX3_YDIR3_3D INVISCIDFLUX3_YDIR3_2D
#define INVISCIDFLUX4_YDIR3_3D INVISCIDFLUX4_YDIR3_2D
#define INVISCIDFLUX5_YDIR3_3D INVISCIDFLUX5_YDIR3_2D
#define INVISCIDFLUX6_YDIR3_3D INVISCIDFLUX6_YDIR3_2D
#define INVISCIDFLUX7_YDIR3_3D INVISCIDFLUX7_YDIR3_2D
#define INVISCIDFLUX8_YDIR3_3D INVISCIDFLUX8_YDIR3_2D

#if 0
  ! Flux in z-direction for ideal MHD in 3D
#endif

#define INVISCIDFLUX1_ZDIR1_3D(U,IDX,u,v,w,p,q)  ZMOMENTUM1(U,IDX)
#define INVISCIDFLUX2_ZDIR1_3D(U,IDX,u,v,w,p,q) (XMOMENTUM1(U,IDX)*w-MYNEWLINE ZMAGFIELD1(U,IDX)* MYNEWLINE XMAGFIELD1(U,IDX))
#define INVISCIDFLUX3_ZDIR1_3D(U,IDX,u,v,w,p,q) (YMOMENTUM1(U,IDX)*w-MYNEWLINE ZMAGFIELD1(U,IDX)* MYNEWLINE YMAGFIELD1(U,IDX))
#define INVISCIDFLUX4_ZDIR1_3D(U,IDX,u,v,w,p,q) (ZMOMENTUM1(U,IDX)*w+p-MYNEWLINE POW(ZMAGFIELD1(U,IDX),2))
#define INVISCIDFLUX5_ZDIR1_3D(U,IDX,u,v,w,p,q) (XMAGFIELD1(U,IDX)*w-MYNEWLINE ZMAGFIELD1(U,IDX)*u)
#define INVISCIDFLUX6_ZDIR1_3D(U,IDX,u,v,w,p,q) (YMAGFIELD1(U,IDX)*w-MYNEWLINE ZMAGFIELD1(U,IDX)*v)
#define INVISCIDFLUX7_ZDIR1_3D(U,IDX,u,v,w,p,q)  RCONST(0.0)
#define INVISCIDFLUX8_ZDIR1_3D(U,IDX,u,v,w,p,q) (TOTALENERGY1(U,IDX)*w+p*w-MYNEWLINE ZMAGFIELD1(U,IDX)*q)

#define INVISCIDFLUX1_ZDIR2_3D(U,IDX,i,n1,n2,u,v,w,p,q)  ZMOMENTUM2(U,IDX,i,n1,n2)
#define INVISCIDFLUX2_ZDIR2_3D(U,IDX,i,n1,n2,u,v,w,p,q) (XMOMENTUM2(U,IDX,i,n1,n2)*w-MYNEWLINE ZMAGFIELD2(U,IDX,i,n1,n2)* MYNEWLINE XMAGFIELD2(U,IDX,i,n1,n2))
#define INVISCIDFLUX3_ZDIR2_3D(U,IDX,i,n1,n2,u,v,w,p,q) (YMOMENTUM2(U,IDX,i,n1,n2)*w-MYNEWLINE ZMAGFIELD2(U,IDX,i,n1,n2)* MYNEWLINE YMAGFIELD2(U,IDX,i,n1,n2))
#define INVISCIDFLUX4_ZDIR2_3D(U,IDX,i,n1,n2,u,v,w,p,q) (ZMOMENTUM2(U,IDX,i,n1,n2)*w+p-MYNEWLINE POW(ZMAGFIELD2(U,IDX,i,n1,n2),2))
#define INVISCIDFLUX5_ZDIR2_3D(U,IDX,i,n1,n2,u,v,w,p,q) (XMAGFIELD2(U,IDX,i,n1,n2)*w-MYNEWLINE ZMAGFIELD2(U,IDX,i,n1,n2)*u)
#define INVISCIDFLUX6_ZDIR2_3D(U,IDX,i,n1,n2,u,v,w,p,q) (YMAGFIELD2(U,IDX,i,n1,n2)*w-MYNEWLINE ZMAGFIELD2(U,IDX,i,n1,n2)*v)
#define INVISCIDFLUX7_ZDIR2_3D(U,IDX,i,n1,n2,u,v,w,p,q)  RCONST(0.0)
#define INVISCIDFLUX8_ZDIR2_3D(U,IDX,i,n1,n2,u,v,w,p,q) (TOTALENERGY2(U,IDX,i,n1,n2)*w+p*w-MYNEWLINE ZMAGFIELD2(U,IDX,i,n1,n2)*q)

#define INVISCIDFLUX1_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q)  ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)
#define INVISCIDFLUX2_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (XMOMENTUM3(U,IDX,i,j,n1,n2,n3)*w-MYNEWLINE ZMAGFIELD3(U,IDX,i,j,n1,n2,n3)* MYNEWLINE XMAGFIELD3(U,IDX,i,j,n1,n2,n3))
#define INVISCIDFLUX3_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (YMOMENTUM3(U,IDX,i,j,n1,n2,n3)*w-MYNEWLINE ZMAGFIELD3(U,IDX,i,j,n1,n2,n3)* MYNEWLINE YMAGFIELD3(U,IDX,i,j,n1,n2,n3))
#define INVISCIDFLUX4_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (ZMOMENTUM3(U,IDX,i,j,n1,n2,n3)*w+p-MYNEWLINE POW(ZMAGFIELD3(U,IDX,i,j,n1,n2,n3),2))
#define INVISCIDFLUX5_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (XMAGFIELD3(U,IDX,i,j,n1,n2,n3)*w-MYNEWLINE ZMAGFIELD3(U,IDX,i,j,n1,n2,n3)*u)
#define INVISCIDFLUX6_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (YMAGFIELD3(U,IDX,i,j,n1,n2,n3)*w-MYNEWLINE ZMAGFIELD3(U,IDX,i,j,n1,n2,n3)*v)
#define INVISCIDFLUX7_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q)  RCONST(0.0)
#define INVISCIDFLUX8_ZDIR3_3D(U,IDX,i,j,n1,n2,n3,u,v,w,p,q) (TOTALENERGY3(U,IDX,i,j,n1,n2,n3)*w+p*w-MYNEWLINE ZMAGFIELD3(U,IDX,i,j,n1,n2,n3)*q)

#if MHD_NDIM == 1

#define INVISCIDFLUX1_XDIR1 INVISCIDFLUX1_XDIR1_1D
#define INVISCIDFLUX2_XDIR1 INVISCIDFLUX2_XDIR1_1D
#define INVISCIDFLUX3_XDIR1 INVISCIDFLUX3_XDIR1_1D
#define INVISCIDFLUX4_XDIR1 INVISCIDFLUX4_XDIR1_1D
#define INVISCIDFLUX5_XDIR1 INVISCIDFLUX5_XDIR1_1D
#define INVISCIDFLUX6_XDIR1 INVISCIDFLUX6_XDIR1_1D
#define INVISCIDFLUX7_XDIR1 INVISCIDFLUX7_XDIR1_1D

#define INVISCIDFLUX1_XDIR2 INVISCIDFLUX1_XDIR2_1D
#define INVISCIDFLUX2_XDIR2 INVISCIDFLUX2_XDIR2_1D
#define INVISCIDFLUX3_XDIR2 INVISCIDFLUX3_XDIR2_1D
#define INVISCIDFLUX4_XDIR2 INVISCIDFLUX4_XDIR2_1D
#define INVISCIDFLUX5_XDIR2 INVISCIDFLUX5_XDIR2_1D
#define INVISCIDFLUX6_XDIR2 INVISCIDFLUX6_XDIR2_1D
#define INVISCIDFLUX7_XDIR2 INVISCIDFLUX7_XDIR2_1D

#define INVISCIDFLUX1_XDIR3 INVISCIDFLUX1_XDIR3_1D
#define INVISCIDFLUX2_XDIR3 INVISCIDFLUX2_XDIR3_1D
#define INVISCIDFLUX3_XDIR3 INVISCIDFLUX3_XDIR3_1D
#define INVISCIDFLUX4_XDIR3 INVISCIDFLUX4_XDIR3_1D
#define INVISCIDFLUX5_XDIR3 INVISCIDFLUX5_XDIR3_1D
#define INVISCIDFLUX6_XDIR3 INVISCIDFLUX6_XDIR3_1D
#define INVISCIDFLUX7_XDIR3 INVISCIDFLUX7_XDIR3_1D

#elif MHD_NDIM == 2

#define INVISCIDFLUX1_XDIR1 INVISCIDFLUX1_XDIR1_2D
#define INVISCIDFLUX2_XDIR1 INVISCIDFLUX2_XDIR1_2D
#define INVISCIDFLUX3_XDIR1 INVISCIDFLUX3_XDIR1_2D
#define INVISCIDFLUX4_XDIR1 INVISCIDFLUX4_XDIR1_2D
#define INVISCIDFLUX5_XDIR1 INVISCIDFLUX5_XDIR1_2D
#define INVISCIDFLUX6_XDIR1 INVISCIDFLUX6_XDIR1_2D
#define INVISCIDFLUX7_XDIR1 INVISCIDFLUX7_XDIR1_2D
#define INVISCIDFLUX8_XDIR1 INVISCIDFLUX8_XDIR1_2D

#define INVISCIDFLUX1_XDIR2 INVISCIDFLUX1_XDIR2_2D
#define INVISCIDFLUX2_XDIR2 INVISCIDFLUX2_XDIR2_2D
#define INVISCIDFLUX3_XDIR2 INVISCIDFLUX3_XDIR2_2D
#define INVISCIDFLUX4_XDIR2 INVISCIDFLUX4_XDIR2_2D
#define INVISCIDFLUX5_XDIR2 INVISCIDFLUX5_XDIR2_2D
#define INVISCIDFLUX6_XDIR2 INVISCIDFLUX6_XDIR2_2D
#define INVISCIDFLUX7_XDIR2 INVISCIDFLUX7_XDIR2_2D
#define INVISCIDFLUX8_XDIR2 INVISCIDFLUX8_XDIR2_2D

#define INVISCIDFLUX1_XDIR3 INVISCIDFLUX1_XDIR3_2D
#define INVISCIDFLUX2_XDIR3 INVISCIDFLUX2_XDIR3_2D
#define INVISCIDFLUX3_XDIR3 INVISCIDFLUX3_XDIR3_2D
#define INVISCIDFLUX4_XDIR3 INVISCIDFLUX4_XDIR3_2D
#define INVISCIDFLUX5_XDIR3 INVISCIDFLUX5_XDIR3_2D
#define INVISCIDFLUX6_XDIR3 INVISCIDFLUX6_XDIR3_2D
#define INVISCIDFLUX7_XDIR3 INVISCIDFLUX7_XDIR3_2D
#define INVISCIDFLUX8_XDIR3 INVISCIDFLUX8_XDIR3_2D


#define INVISCIDFLUX1_YDIR1 INVISCIDFLUX1_YDIR1_2D
#define INVISCIDFLUX2_YDIR1 INVISCIDFLUX2_YDIR1_2D
#define INVISCIDFLUX3_YDIR1 INVISCIDFLUX3_YDIR1_2D
#define INVISCIDFLUX4_YDIR1 INVISCIDFLUX4_YDIR1_2D
#define INVISCIDFLUX5_YDIR1 INVISCIDFLUX5_YDIR1_2D
#define INVISCIDFLUX6_YDIR1 INVISCIDFLUX6_YDIR1_2D
#define INVISCIDFLUX7_YDIR1 INVISCIDFLUX7_YDIR1_2D
#define INVISCIDFLUX8_YDIR1 INVISCIDFLUX8_YDIR1_2D

#define INVISCIDFLUX1_YDIR2 INVISCIDFLUX1_YDIR2_2D
#define INVISCIDFLUX2_YDIR2 INVISCIDFLUX2_YDIR2_2D
#define INVISCIDFLUX3_YDIR2 INVISCIDFLUX3_YDIR2_2D
#define INVISCIDFLUX4_YDIR2 INVISCIDFLUX4_YDIR2_2D
#define INVISCIDFLUX5_YDIR2 INVISCIDFLUX5_YDIR2_2D
#define INVISCIDFLUX6_YDIR2 INVISCIDFLUX6_YDIR2_2D
#define INVISCIDFLUX7_YDIR2 INVISCIDFLUX7_YDIR2_2D
#define INVISCIDFLUX8_YDIR2 INVISCIDFLUX8_YDIR2_2D

#define INVISCIDFLUX1_YDIR3 INVISCIDFLUX1_YDIR3_2D
#define INVISCIDFLUX2_YDIR3 INVISCIDFLUX2_YDIR3_2D
#define INVISCIDFLUX3_YDIR3 INVISCIDFLUX3_YDIR3_2D
#define INVISCIDFLUX4_YDIR3 INVISCIDFLUX4_YDIR3_2D
#define INVISCIDFLUX5_YDIR3 INVISCIDFLUX5_YDIR3_2D
#define INVISCIDFLUX6_YDIR3 INVISCIDFLUX6_YDIR3_2D
#define INVISCIDFLUX7_YDIR3 INVISCIDFLUX7_YDIR3_2D
#define INVISCIDFLUX8_YDIR3 INVISCIDFLUX8_YDIR3_2D

#elif MHD_NDIM == 3

#define INVISCIDFLUX1_XDIR1 INVISCIDFLUX1_XDIR1_3D
#define INVISCIDFLUX2_XDIR1 INVISCIDFLUX2_XDIR1_3D
#define INVISCIDFLUX3_XDIR1 INVISCIDFLUX3_XDIR1_3D
#define INVISCIDFLUX4_XDIR1 INVISCIDFLUX4_XDIR1_3D
#define INVISCIDFLUX5_XDIR1 INVISCIDFLUX5_XDIR1_3D
#define INVISCIDFLUX6_XDIR1 INVISCIDFLUX6_XDIR1_3D
#define INVISCIDFLUX7_XDIR1 INVISCIDFLUX7_XDIR1_3D
#define INVISCIDFLUX8_XDIR1 INVISCIDFLUX8_XDIR1_3D

#define INVISCIDFLUX1_XDIR2 INVISCIDFLUX1_XDIR2_3D
#define INVISCIDFLUX2_XDIR2 INVISCIDFLUX2_XDIR2_3D
#define INVISCIDFLUX3_XDIR2 INVISCIDFLUX3_XDIR2_3D
#define INVISCIDFLUX4_XDIR2 INVISCIDFLUX4_XDIR2_3D
#define INVISCIDFLUX5_XDIR2 INVISCIDFLUX5_XDIR2_3D
#define INVISCIDFLUX6_XDIR2 INVISCIDFLUX6_XDIR2_3D
#define INVISCIDFLUX7_XDIR2 INVISCIDFLUX7_XDIR2_3D
#define INVISCIDFLUX8_XDIR2 INVISCIDFLUX8_XDIR2_3D

#define INVISCIDFLUX1_XDIR3 INVISCIDFLUX1_XDIR3_3D
#define INVISCIDFLUX2_XDIR3 INVISCIDFLUX2_XDIR3_3D
#define INVISCIDFLUX3_XDIR3 INVISCIDFLUX3_XDIR3_3D
#define INVISCIDFLUX4_XDIR3 INVISCIDFLUX4_XDIR3_3D
#define INVISCIDFLUX5_XDIR3 INVISCIDFLUX5_XDIR3_3D
#define INVISCIDFLUX6_XDIR3 INVISCIDFLUX6_XDIR3_3D
#define INVISCIDFLUX7_XDIR3 INVISCIDFLUX7_XDIR3_3D
#define INVISCIDFLUX8_XDIR3 INVISCIDFLUX8_XDIR3_3D


#define INVISCIDFLUX1_YDIR1 INVISCIDFLUX1_YDIR1_3D
#define INVISCIDFLUX2_YDIR1 INVISCIDFLUX2_YDIR1_3D
#define INVISCIDFLUX3_YDIR1 INVISCIDFLUX3_YDIR1_3D
#define INVISCIDFLUX4_YDIR1 INVISCIDFLUX4_YDIR1_3D
#define INVISCIDFLUX5_YDIR1 INVISCIDFLUX5_YDIR1_3D
#define INVISCIDFLUX6_YDIR1 INVISCIDFLUX6_YDIR1_3D
#define INVISCIDFLUX7_YDIR1 INVISCIDFLUX7_YDIR1_3D
#define INVISCIDFLUX8_YDIR1 INVISCIDFLUX8_YDIR1_3D

#define INVISCIDFLUX1_YDIR2 INVISCIDFLUX1_YDIR2_3D
#define INVISCIDFLUX2_YDIR2 INVISCIDFLUX2_YDIR2_3D
#define INVISCIDFLUX3_YDIR2 INVISCIDFLUX3_YDIR2_3D
#define INVISCIDFLUX4_YDIR2 INVISCIDFLUX4_YDIR2_3D
#define INVISCIDFLUX5_YDIR2 INVISCIDFLUX5_YDIR2_3D
#define INVISCIDFLUX6_YDIR2 INVISCIDFLUX6_YDIR2_3D
#define INVISCIDFLUX7_YDIR2 INVISCIDFLUX7_YDIR2_3D
#define INVISCIDFLUX8_YDIR2 INVISCIDFLUX8_YDIR2_3D

#define INVISCIDFLUX1_YDIR3 INVISCIDFLUX1_YDIR3_3D
#define INVISCIDFLUX2_YDIR3 INVISCIDFLUX2_YDIR3_3D
#define INVISCIDFLUX3_YDIR3 INVISCIDFLUX3_YDIR3_3D
#define INVISCIDFLUX4_YDIR3 INVISCIDFLUX4_YDIR3_3D
#define INVISCIDFLUX5_YDIR3 INVISCIDFLUX5_YDIR3_3D
#define INVISCIDFLUX6_YDIR3 INVISCIDFLUX6_YDIR3_3D
#define INVISCIDFLUX7_YDIR3 INVISCIDFLUX7_YDIR3_3D
#define INVISCIDFLUX8_YDIR3 INVISCIDFLUX8_YDIR3_3D


#define INVISCIDFLUX1_ZDIR1 INVISCIDFLUX1_ZDIR1_3D
#define INVISCIDFLUX2_ZDIR1 INVISCIDFLUX2_ZDIR1_3D
#define INVISCIDFLUX3_ZDIR1 INVISCIDFLUX3_ZDIR1_3D
#define INVISCIDFLUX4_ZDIR1 INVISCIDFLUX4_ZDIR1_3D
#define INVISCIDFLUX5_ZDIR1 INVISCIDFLUX5_ZDIR1_3D
#define INVISCIDFLUX6_ZDIR1 INVISCIDFLUX6_ZDIR1_3D
#define INVISCIDFLUX7_ZDIR1 INVISCIDFLUX7_ZDIR1_3D
#define INVISCIDFLUX8_ZDIR1 INVISCIDFLUX8_ZDIR1_3D

#define INVISCIDFLUX1_ZDIR2 INVISCIDFLUX1_ZDIR2_3D
#define INVISCIDFLUX2_ZDIR2 INVISCIDFLUX2_ZDIR2_3D
#define INVISCIDFLUX3_ZDIR2 INVISCIDFLUX3_ZDIR2_3D
#define INVISCIDFLUX4_ZDIR2 INVISCIDFLUX4_ZDIR2_3D
#define INVISCIDFLUX5_ZDIR2 INVISCIDFLUX5_ZDIR2_3D
#define INVISCIDFLUX6_ZDIR2 INVISCIDFLUX6_ZDIR2_3D
#define INVISCIDFLUX7_ZDIR2 INVISCIDFLUX7_ZDIR2_3D
#define INVISCIDFLUX8_ZDIR2 INVISCIDFLUX8_ZDIR2_3D

#define INVISCIDFLUX1_ZDIR3 INVISCIDFLUX1_ZDIR3_3D
#define INVISCIDFLUX2_ZDIR3 INVISCIDFLUX2_ZDIR3_3D
#define INVISCIDFLUX3_ZDIR3 INVISCIDFLUX3_ZDIR3_3D
#define INVISCIDFLUX4_ZDIR3 INVISCIDFLUX4_ZDIR3_3D
#define INVISCIDFLUX5_ZDIR3 INVISCIDFLUX5_ZDIR3_3D
#define INVISCIDFLUX6_ZDIR3 INVISCIDFLUX6_ZDIR3_3D
#define INVISCIDFLUX7_ZDIR3 INVISCIDFLUX7_ZDIR3_3D
#define INVISCIDFLUX8_ZDIR3 INVISCIDFLUX8_ZDIR3_3D

#else

#ifdef MHD_NDIM
#error "Invalid spatial dimension specified!"
#endif

#endif

#endif
