//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cException.cpp
//  @ Date : 31.08.2006
//  @ Author : Raphael M�nster
//
//


#include <exception.h>


cException::cException(string strFile, unsigned int iLine, string strError): m_strFile(strFile), m_iLine(iLine), m_strError(strError)
{

}

void cException::writeMessage()
{
	cout<<m_strError<<":"<<endl;
	cout<<"In line: "<<m_iLine<<" in file: "<<m_strFile<<endl;
}

cKnotSpanException::cKnotSpanException(string strFile, unsigned int iLine, string strError, double dinvalidValue)
										:cException(strFile, iLine, strError)
{
	m_dinvalidValue = dinvalidValue;
}

void cKnotSpanException::writeMessage()
{
	cout<<m_strError<<":"<<endl;
	cout<<"Invalid parameter value: "<<m_dinvalidValue<<endl;
	cout<<"In line: "<<m_iLine<<" in file: "<<m_strFile<<endl;
}