***********************************************************************
* This header file declares all functions that are used
* in the dynamic string handling implementation.
***********************************************************************

      INTEGER  STNEWL,STLEN,STDUP,STLEF,STRIG,STMID,STNEWC,STCMP,STNCM
      INTEGER  STCHR,STRCH,STSTR
      EXTERNAL STNEWL,STLEN,STDUP,STLEF,STRIG,STMID,STNEWC,STCMP,STNCM
      EXTERNAL STCHR,STRCH,STSTR

      CHARACTER STGCH,TOUPRC,TOLWRC
      EXTERNAL STGCH,TOUPRC,TOLWRC
      